import random

animales = [
'Canguro rojo','Koala','Dingo','Wombat','Emu','Equidna','Tasmanian Devil','Quoll','Possum','Wallaby','Ornitorrinco','Petauro del azucar','Equidna de hocico largo','Bandicoot','Zarigiueya','Cacatua','Aves del parai­so','Equidna de pico corto','Serpiente taipán','Serpiente marron','Serpiente tigre','Serpiente de cascabel','Serpiente de coral','Serpiente negra oriental','Serpiente del norte de Australia','Serpiente venenosa de vientre rojo','Serpiente marron comun','Serpiente de vientre amarillo','Serpiente marina','Sea Snake','Serpiente de barriga pálida',
'Calamar','Foca','Delfi­n','Pez leon','Leon Marino','Cachalote','Ballena franca','Ancistrus comun',	'Ballena azul','Anguila electrica','Medusa','Ballena gris','Pepino de mar','Sepia','Tiburon ballena','Sardinas','Gamba','Calderon comun','Manati','Trucha comun','Ci­clico nacarado','Pulpo','Pulpo de anillos azules','Tetra de Aleta Sangrante','Pez arquero','Pez cola de espada','Caracol de mar','Pez sapo peludo','Pez luna','Tiburon blanco','Arenques','Ci­clido cebra','Dragon de mar','Carpas','Pez espada','Tortuga marina','Tetra caverni­cola','Pez globo','Pez mariposa','Langosta',
'Carpa dorada','Pez loro','Atun','Cerdo marino','Salmon','Almeja','Coral','Rodaballo','Tortuga','Mojarrita','Pez oscar','Piraña','Marsopa','Pez volador','Boca de fuego','Tintorera','Pinguino','Bacalao','Necora','Acara azul','Caballito de mar','Mejillon','Salmones','Estrella de mar','Orca','Pez telescopio','Pez oso',	'Erizo de mar','Surubi­','Camello','Lobo','Topo','Liebre','Pantera','Gallina','Gato','Perro','Tarantula','Oveja','Cerdo','Iguana','Bufalo','Gusano','Mapache','Alce','Escorpion','Elefante','Dromedario','Venado' ,'Oso Polar','Araña','Rinoceronte','Mula','Orangután',
'Rata','Chita','Avestruz','Leopardo','Gorila','Serpiente','Ganso','Raton','Cocodrilo','Tigre','Anaconda','Gallo','Ñandu','Caballo','Pinguino','Cabra','Jaguar','Vaca','Vi­bora','Castor','Rana Canguro Hámster','Conejo Asno Lagartija','Becerro Alacrán Mandril','Armadillo Caimán Oso','Camaleon Tortuga Viuda','Koala Ardilla Hormiga','Burro Jirafa Leon','Mono Chango Toro','Tejones' ,'Osos','Murcielagos','Abejas','Ardillas Lombrices','Ardillas rayadas',	'Golondrina','Perrito de las pradera',	'Lagartos','Marmotas' ,'Cigiueña','Mapaches','Serpientes','Mofetas',
'Babosas terestres' ,'Culebrilla ciega' ,'Caracoles marinos','Tortuga marina','Nereis','Basilisco verde','Piton','Gusarapa','Miñoca','Navaja','Palolo',	'Caimán','Labaria','Vi­bora hocicuda','Serpiente','Ostiones u ostras'	,'Cocodrilo','Lombriz de tierra','Dragon de Komodo','Camaleon','Tortuga laud','Sanguijuela','Babosas marinas','Caracoles terrestres','Equidna de hocico corto','Petauro del plomo','Quokka','Dibbler','Numbat','Bowerbird','Cacatua negra','Tawny Frogmouth','Glider del azucar del sur','Flying Squirrel','Atrapamoscas lira'
]

colores = [
'Aguamarina','Alabastro','Albaricoque','Alheli','Alizarina','Almendra','Amaranto','Amarillo','Amarillo ambar','Amarillo anaranjado','Amarillo anemona','Amarillo aureo','Amarillo brillante','Amarillo bronceado','Amarillo canario','Amarillo claro','Amarillo cobrizo','Amarillo dorado','Amarillo dorado brillante','Amarillo dorado cegador','Amarillo dorado centelleador','Amarillo dorado centelleante','Amarillo dorado chispeante','Amarillo dorado claro','Amarillo dorado deslumbrador','Amarillo dorado deslumbrante',
'Amarillo dorado destellante','Amarillo dorado esplendoroso','Amarillo dorado fulgente','Amarillo dorado fulgurador','Amarillo dorado fulgurante','Amarillo dorado incandescente','Amarillo dorado intenso','Amarillo dorado irisado','Amarillo dorado irisador','Amarillo dorado luminiscente','Amarillo dorado luminoso','Amarillo dorado lustroso','Amarillo dorado mate','Amarillo dorado metalico','Amarillo dorado oscuro','Amarillo dorado palido','Amarillo dorado radiante','Amarillo dorado refulgente','Amarillo dorado refulgidor',
'Amarillo dorado reluciente','Amarillo dorado relumbrante','Amarillo dorado resplandecente','Amarillo dorado resplandecidor','Amarillo dorado resplandeciente','Amarillo dorado resplendente','Amarillo dorado resplendidor','Amarillo dorado titilador','Amarillo dorado titilante','Amarillo intenso','Amarillo limon','Amarillo maiz','Amarillo mostaza','Amarillo neon','Amarillo ocre','Amarillo oro','Amarillo oscuro','Amarillo palido','Amarillo palo','Amarillo pastel','Amarillo primavera','Amarillo siena','Amarillo suave',
'Amarillo tenue','Amarillo topacio','Amarillo verdoso','Amatista','Amatista claro','Amatista oscuro','Anaranjado','Anaranjado ambar','Anaranjado brillante','Anaranjado calido','Anaranjado claro','Anaranjado frio','Anaranjado intenso','Anaranjado neon','Anaranjado oscuro','Anaranjado suave','Anemona','Antracita','Avellana','Azabache','Azufre','Azul','Azul Klein','Azul Tiffany','Azul aciano','Azul arandano','Azul añil','Azul bebe','Azul berilo','Azul celeste','Azul cerulean','Azul ceruleo','Azul cian',
'Azul cielo','Azul claro','Azul cobalto','Azul electrico','Azul glacial','Azul hielo','Azul klein','Azul lapislazuli','Azul marino','Azul medianoche','Azul pastel','Azul pavo real','Azul periwinkle','Azul petroleo','Azul pizarra','Azul polvo','Azul prusia','Azul real','Azul tinta','Azul topacio','Azul turquesa','Azul ultramar','Azul ultramarino','Azul verdoso','Azul violaceo','Azul violeta','Azul yodo','Azul zafiro','Añil','Beige','Beige claro','Beige oscuro','Beige rosado','Beis','Berenjena','Berenjena claro','Berenjena oscuro',
'Bermellon','Blanco','Blanco alabastro','Blanco antiguo','Blanco hueso','Blanco humo','Blanco marfil','Blanco nacar','Blanco nieve','Blanco perla','Blanco puro','Blanco tiza','Borgoña','Borgoña claro','Borgoña oscuro','Borgoña profundo','Brillante','Bronce','Bronce oscuro','Bronceado','Bronceado claro','Bronceado oscuro','Bronceado profundo','Burdeos','Burdeos claro','Burdeos oscuro','Cacao','Cafe','Cafe claro','Cafe oscuro','Canario','Caoba','Caoba claro',   'Caoba oscuro','Caoba profundo','Caqui','Caramelo','Caramelo claro',
'Caramelo oscuro','Caramelo profundo','Carmesi','Carmesi claro','Carmesi oscuro','Carmesi profundo','Carmin','Castaño','Celeste','Ceniza','Cereza','Cereza claro','Cereza oscura','Cereza oscuro','Cereza profundo','Cian','Cian claro','Cian oscuro','Cian profundo','Ciruela','Ciruela claro','Ciruela oscuro','Ciruela profundo','Claro','Cobre','Cobrizo','Coral','Coral claro','Coral oscuro','Coral profundo','Crema','Crema clara','Crema claro','Crema oscura','Crema oscuro','Crema profundo','Cromo','Cuarzo rosa','Cuarzo rosa claro',
'Cuarzo rosa oscuro','Cuarzo rosa profundo','Dorado','Dorado claro','Dorado oscuro','Dorado profundo','Escarlata','Esmeralda','Esmeralda claro','Esmeralda oscuro','Esmeralda profundo','Frambuesa','Fucsia','Fucsia claro','Fucsia oscuro','Fucsia profundo','Granate','Gris','Gris claro','Gris marengo','Gris oscuro','Gris perla','Gris perla claro','Gris perla oscuro','Gris perla profundo','Gris profundo','Gris topo','Intenso','Jade','Jazmin','Ladrillo','Lavanda','Lavanda claro','Lavanda oscuro','Lavanda profundo','Lila','Lima',
'Lima claro','Lima oscuro','Lima profundo','Limon','Magenta','Magenta claro','Magenta oscuro','Magenta profundo','Maiz','Malva','Malva claro','Malva oscuro','Malva profundo','Mandarina','Marfil','Marfil claro','Marfil oscuro','Marfil profundo','Marron','Marron chocolate','Marron claro','Marron oscuro','Marron profundo','Mauve','Melocoton','Melocoton claro','Melocoton oscuro','Menta','Morado','Mostaza','Mostaza claro','Mostaza oscuro','Mostaza profundo','Naranja','Naranja claro','Naranja intenso','Naranja oscuro','Naranja profundo',
'Naranja quemado','Negro','Neon','Ocre','Oliva','Oro','Oro claro','Oro oscuro','Oro profundo','Oro viejo','Oscuro','Palido','Pardo','Pardo claro','Pardo oscuro','Pardo profundo','Pastel','Perla','Plateado','Purpura','Purpura claro','Purpura oscuro','Purpura profundo','Rojo','Rojo brillante','Rojo carmesi','Rojo claro','Rojo escarlata','Rojo intenso','Rojo neon','Rojo oscuro','Rojo profundo','Rojo rubi','Rojo suave','Rosa','Rosa claro','Rosa oscuro','Rosa pastel','Rosa profundo','Rubi','Rubi claro','Rubi oscuro','Rubi profundo',
'Salmon','Salmon claro','Salmon oscuro','Salmon profundo','Sepia','Sepia claro','Sepia oscuro','Sepia profundo','Suave','Teal','Teal claro','Teal oscuro','Teal profundo','Terracota','Terracota claro','Tiza','Topacio','Turquesa','Turquesa claro','Turquesa oscuro','Turquesa profundo','Uva','Uva claro','Uva oscuro','Uva profundo','Vainilla','Verde','Verde agua','Verde agua claro','Verde agua oscuro','Verde agua profundo','Verde azulado','Verde azulado claro','Verde azulado oscuro','Verde azulado profundo','Verde bosque',
'Verde bosque claro','Verde bosque oscuro','Verde bosque profundo','Verde botella','Verde botella claro','Verde botella oscuro','Verde botella profundo','Verde caza','Verde caza claro','Verde caza oscuro','Verde caza profundo','Verde claro','Verde claro claro','Verde claro oscuro','Verde claro profundo','Verde esmeralda','Verde esmeralda claro','Verde esmeralda oscuro','Verde esmeralda profundo','Verde hierba','Verde hierba claro','Verde hierba oscuro','Verde hierba profundo','Verde jade','Verde jade claro','Verde jade oscuro',
'Verde jade profundo','Verde lima','Verde lima claro','Verde lima oscuro','Verde lima profundo','Verde limon','Verde limon claro','Verde limon oscuro','Verde limon profundo','Verde manzana','Verde manzana claro','Verde manzana oscuro','Verde manzana profundo','Verde mar','Verde mar claro','Verde mar oscuro','Verde mar profundo','Verde marino','Verde marino claro','Verde marino oscuro','Verde marino profundo','Verde menta','Verde menta claro','Verde menta oscuro','Verde menta profundo','Verde militar','Verde militar claro',
'Verde militar oscuro','Verde militar profundo','Verde musgo','Verde musgo claro','Verde musgo oscuro','Verde musgo profundo','Verde oliva','Verde oliva claro','Verde oliva oscuro','Verde oliva profundo','Verde oscuro','Verde oscuro claro','Verde oscuro oscuro','Verde oscuro profundo','Verde palido','Verde palido claro','Verde palido oscuro','Verde palido profundo','Verde pastel','Verde pastel claro','Verde pastel oscuro','Verde pastel profundo','Verde pino','Verde pino claro','Verde pino oscuro','Verde pino profundo','Verde pistacho',
'Verde pistacho claro','Verde pistacho oscuro','Verde pistacho profundo','Verde primavera','Verde primavera claro','Verde primavera oscuro','Verde primavera profundo','Verde profundo','Verde salvia','Verde salvia claro','Verde salvia oscuro','Verde salvia profundo','Verde selva','Verde selva claro','Verde selva oscuro','Verde selva profundo','Vino','Violeta','Zanahoria','aguamarina,menta','albaricoque','amaranto','amarillo','amarillo indio,topacio','amarillo limon o lima','amarillo selectivo','amatista','ambar','arlequin','azul acero claro',
'azul Klein','azul cobalto','azul de Prusia','azul majorelle','azul marino','azul petroleo','azur,azul francia','añil,indigo','beis,beige','bermellon','blanco','borgoña','caqui','cara de luz','carmesi,rubi,frutilla','carmin','celeste','ceruleo','chartreuse','cian','durazno,piel','escarlata','esmeralda,verde agua,verdeagua,agua marina','esparrago','fucsia','granate,burdeos','gris','jade','lavanda','lavanda floral','lila','magenta','malva','marron,pardo,cafe,chocolate,castaño','morado','naranja','negro','nieve','nieve blanca','lino','hueso',
'marfil','ocre','oro,dorado','plata,plateado','purpura de Tiro','rojo,colorado','rosa','salmon','siena','siena palido','turquesa','turqui','verde','verde Kelly','verde cazador,verde militar','verde oliva','verde verones','verdeceledon','violeta','xanadu','zafiro','zanahoria 	sesamo','zinc','Ámbar','Ámbar claro','Ámbar oscuro','Ámbar palido','Índigo','Índigo claro','Índigo oscuro','Índigo profundo','Ópalo','Ópalo claro','Ópalo oscuro','Ópalo profundo'
]

comidas = [
'Albaricoque', 'Albondigas', 'Arandano', 'Arroz con pollo', 'Arroz frito', 'Batidos', 'Burritos', 'Caqui', 'Carambola', 'Carnes a la parrilla', 'Cereza', 'Ceviche', 'Chirimoya', 'Ciruela', 'Ciruela pasa', 'Coco', 'Costillas a la barbacoa', 'Crema catalana', 'Crepes', 'Croissants', 'Curry', 'Donas', 'Durian', 'Empanadas', 'Ensalada', 'Ensalada de frutas', 'Fajitas', 'Filete de ternera', 'Flan', 'Frambuesa', 'Fresa', 'Frutas frescas', 'Galletas', 'Gazpacho', 'Granada', 'Grosella', 'Guanabana', 'Guayaba', 'Guiso de carne',
'Hamburguesa', 'Helado', 'Higo', 'Jicama', 'Kiwi', 'Kumquat', 'Lasaña', 'Lichi', 'Limon', 'Magdalenas', 'Mandarina', 'Mango', 'Mangostan', 'Manzana', 'Maracuya', 'Melocoton', 'Melon', 'Membrillo', 'Mora', 'Moras', 'Muffins', 'Naranja', 'Natillas', 'Nectarina', 'Nispero', 'Paella', 'Papaya', 'Pasta', 'Pastel de chocolate', 'Pasteles', 'Pepino', 'Pepino dulce', 'Pera', 'Pescado al horno', 'Pimientos rellenos', 'Pitahaya', 'Pizza', 'Piña', 'Platano', 'Pollo asado', 'Pomelo', 'Risotto', 'Sandia', 'Sandwich', 'Sandwich de pavo', 'Sopa de fideos',
'Sopa de tomate', 'Sopa de verduras', 'Sushi', 'Tacos', 'Tamarindo', 'Tarta de manzana', 'Tarta de queso', 'Tiramisu', 'Tortilla española', 'Uchuva', 'Uva', 'Yogur con granola', 'Zarzamora', 'Banana'
]

coordenadas = [
'Norte','Sur','Este','Oeste'
]

herramientas = [ 
'Abrazadera', 'Alicate', 'Alicates', 'Alicates de punta larga', 'Azada', 'Broca', 'Broca Forstner', 'Broca de diamante', 'Broca de pala', 'Broca escalonada', 'Broca helicoidal', 'Brocha', 'Caladora', 'Calibre', 'Calibre digital', 'Calibre vernier', 'Cepillo', 'Cepillo de alambre', 'Cepillo de carpintero', 'Cincel', 'Cincel de madera', 'Cincel para madera', 'Cincel para metal', 'Cincel para piedra', 'Cinta', 'Cinta metrica', 'Cizalla', 'Clavo', 'Compas de precision', 'Cortafrios', 'Cortatubos', 'Cuchillo', 'Cuchillo de utilidad',
'Destornillador', 'Destornillador de estrella', 'Destornillador de impacto', 'Destornillador de punta plana', 'Detector de metales', 'Detector de voltaje', 'Doblador de tubos', 'El arado', 'El cuchillo', 'El serrucho.', 'Escalera', 'Escoba', 'Escuadra', 'Espatula', 'Extractor de rodamientos', 'Extractor de tuercas', 'Flexometro', 'Formon', 'Gafas de proteccion', 'Gato hidraulico', 'Grapadora', 'Grapadora neumatica', 'Guantes de trabajo', 'Gubia', 'Hacha', 'Hoja de sierra para caladora', 'Hoja de sierra para sable', 'Juego de llaves Allen', 'Juego de llaves de vaso',
'La brujula', 'La hoz', 'Lapiz de carpintero', 'Lijadora', 'Lijadora de banda', 'Lijadora de mano electrica', 'Lijadora delta', 'Lijadora orbital', 'Lima', 'Lima plana', 'Lima redonda', 'Lima triangular', 'Linterna', 'Llana de albañil', 'Llave', 'Llave Allen', 'Llave de carraca', 'Llave de impacto', 'Llave de pipa', 'Llave de tubo', 'Llave de tubo ajustable', 'Llave de vaso', 'Llave dinamometrica', 'Llave inglesa', 'Machete', 'Mandril', 'Martillo', 'Martillo de bola', 'Martillo de carpintero', 'Martillo de goma', 'Martillo demoledor', 'Martillo percutor', 'Maza',
'Medidor de angulos', 'Metro', 'Metro de carpintero', 'Metro plegable', 'Micrometro', 'Multimetro', 'Nipleador', 'Nivel', 'Nivel de burbuja', 'Nivel de plomada', 'Nivel laser', 'Nivel magnetico', 'Pala', 'Paleta de albañil', 'Pico', 'Pie de rey', 'Pinza', 'Pinza de presion', 'Pinzas', 'Pistola de calor', 'Pistola de clavos', 'Pistola de silicona', 'Prensa', 'Prensa de carpintero', 'Prensa de tornillo', 'Punzon', 'Remachadora', 'Remachadora de mano', 'Rodillo', 'Sacaclavos', 'Sargento', 'Segueta', 'Serrucho', 'Serrucho japones', 'Sierra', 'Sierra circular',
'Sierra de arco', 'Sierra de calar', 'Sierra de cinta', 'Sierra de mano', 'Sierra de mano para carpinteria', 'Sierra de mano para jardin', 'Sierra de mano para metales', 'Sierra de mesa', 'Sierra de sable', 'Sierra ingletadora', 'Sierra para azulejos', 'Sierra para huesos', 'Sierra para pladur', 'Soplete', 'Soplete de gas', 'Soplete de soldadura', 'Taladro', 'Taladro atornillador', 'Taladro de mano', 'Tenazas', 'Tijeras', 'Tijeras de chapa', 'Tornillo', 'Torno'
]

hijos = [
'hijo unico','mellizo','trillizo','cuatrillizo','quintillizo','gemelo','siames'
]

materiales = [
'Acero', 'Acrilico', 'Acrilonitrilo Butadieno Estireno', 'Aglomerado', 'Aglomerado de fibras', 'Alambre', 'Alquitran', 'Aluminio', 'Amianto', 'Arcilla', 'Arcilla expandida', 'Arena', 'Arenisca', 'Asfalto', 'Bambu', 'Bambu laminado', 'Barro', 'Basalto', 'Betun', 'Bronce', 'Carton', 'Caucho', 'Cera', 'Ceramica', 'Ceramica sin vidriar', 'Ceramica vidriada', 'Cobre', 'Composite', 'Corcho', 'Corcho aglomerado', 'Corcho expandido', 'Corcho natural', 'Cuarcita', 'Cuarzo', 'Cuero', 'Espuma', 'Espuma de latex', 'Espuma de memoria', 'Espuma de poliestireno',
'Espuma de poliuretano', 'Fibra de carbono', 'Fibra de vidrio', 'Fibra de vidrio reforzada con plastico', 'Fibrocemento', 'Goma', 'Gomaespuma', 'Granito', 'Granito artificial', 'Grava', 'Hierro', 'Hormigon', 'Ladrillo', 'Latex', 'Laton', 'Madera', 'Madera blanda', 'Madera contrachapada', 'Madera contrachapada fenolica', 'Madera dura', 'Madera laminada', 'Madera prensada', 'Marmol', 'Marmol artificial', 'Metal', 'Metal corrugado', 'Metal forjado', 'Metal fundido', 'Metal galvanizado', 'Metal oxidado', 'Metal perforado', 'Metal pintado', 'Metal pulido', 'Neopreno', 'Nylon',
'PVC', 'Papel', 'Parafina', 'Perlita', 'Piedra', 'Piedra caliza', 'Pizarra', 'Plastico', 'Plastico ABS', 'Plastico ABS reforzado con fibra de vidrio', 'Plastico de alta temperatura', 'Plastico reciclado', 'Plastico reforzado con fibra de vidrio', 'Plexiglas', 'Poliacrilonitrilo', 'Poliamida', 'Policarbonato', 'Poliester', 'Poliester reforzado con fibra de vidrio', 'Poliestireno', 'Poliestireno expandido', 'Poliestireno extruido', 'Polietileno', 'Polimero', 'Polimero reforzado con fibra de carbono', 'Polimetilmetacrilato', 'Polipropileno', 'Polipropileno expandido', 'Poliuretano',
'Polvo de marmol', 'Porcelana', 'Rattan', 'Rattan trenzado', 'Resina', 'Resina acrilica', 'Resina de epoxy', 'Resina de fibra de carbono', 'Resina de fibra de vidrio', 'Resina de melamina', 'Resina de poliester', 'Resina de poliuretano', 'Resina de silicona', 'Resina de uretano', 'Resina epoxi', 'Resina fenolica', 'Resina termoestable', 'Resina termofija', 'Resina termoplastica', 'Resina vinilica', 'Serpentina', 'Silicona', 'Teflon', 'Tela', 'Terracota', 'Titanio', 'Travertino', 'Vermiculita', 'Vidrio', 'Vinilo', 'Vinilo reforzado con fibra de vidrio', 'Yeso', 'Zeolita'
]

signos = [
'Aries','Tauro','Géminis','Cáncer','Leo','Virgo','Libra','Escorpio','Sagitario','Capricornio','Acuario','Piscis','Arianos','Arianas','Géminis','Cancerianos','Cancerianas','Virginianos','Virginianas','Librianos','Librianas','Escorpianos','Escorpianas','Sagitarianos','Sagitarianas','Acuarianos','Acuarianas','Piscianos','Piscianas'
]

war = [
    'Alferez', 'Cabo', 'Capitan', 'Coronel', 'General de brigada', 'General de ejercito o mariscal', 'Mayor', 'Mayor general', 'Sargento', 'Sargento primero', 'Soldado', 'Suboficial', 'Teniente', 'Teniente coronel', 'Teniente general'
]

dioses = [
'Aegir', 'Afrodita', 'Agni ', 'Amaterasu', 'Amaterasu-Ōmikami', 'Amon', 'Anansi', 'Andromeda', 'Anfion', 'Anhur', 'Anubis', 'Anuket', 'Apolo', 'Aquiles', 'Ares', 'Argos', 'Ariadna', 'Artemisa', 'Atalanta', 'Atenea', 'Atlas', 'Atum', 'Balder', 'Baldur', 'Bast', 'Bastet', 'Benten', 'Benzaiten', 'Bishamonten', 'Bragi', 'Brahma ', 'Caliope', 'Camazotz', 'Ceres', 'Chaac', 'Chalchiuhtlicue', 'Circe', 'Coatlicue', 'Cronos', 'Dafne', 'Dagr', 'Daikoku', 'Dedalo', 'Demeter', 'Dionisio', 'Durga ', 'Ebisu', 'Eir', 'Electra', 'Eleggua', 'Eneas', 'Eolo', 'Eros', 'Faeton',
'Fauno', 'Fenix', 'Fenrir', 'Forseti', 'Freya', 'Freyja', 'Freyr', 'Frigg', 'Fujin', 'Ganesha ', 'Garuda ', 'Gea', 'Geb', 'Hachiman', 'Hades', 'Hanuman ', 'Hapi', 'Hathor', 'Hecate', 'Hector', 'Hefesto', 'Heimdall', 'Hel', 'Hela', 'Helena', 'Hera', 'Heracles', 'Hercules', 'Hermes', 'Horus', 'Huitzilopochtli', 'Hunab Ku', 'Idun', 'Idunn', 'Inari', 'Indra ', 'Isis', 'Itzpapalotl', 'Ixchel', 'Izanagi', 'Izanami', 'Jason', 'Jizo', 'Jormungandr', 'Kagutsuchi', 'Kali ', 'Karna ', 'Khnum', 'Khonsu', 'Krishna ', 'Kubera ', 'Kukulkan', 'Lakshmi ', 'Loki', 'Ma\'at', 'Maahes', 'Maat',
'Mami Wata', 'Medusa', 'Mictecacihuatl', 'Midas', 'Mimir', 'Minerva', 'Minotauro', 'Mixcoatl', 'Morfeo', 'Narciso', 'Neith', 'Nemesis', 'Njord', 'Nut', 'Obatala', 'Odin', 'Odiseo', 'Ogun', 'Omoikane', 'Orfeo', 'Oshun', 'Osiris', 'Oya', 'Pan', 'Pandora', 'Paris', 'Parvati ', 'Penelope', 'Persefone', 'Perseo', 'Poseidon', 'Prometeo', 'Proteo', 'Ptah', 'Quetzalcoatl', 'Quiron', 'Ra', 'Raijin', 'Rama ', 'Ran', 'Saraswati ', 'Seker', 'Sekhmet', 'Serapis', 'Set', 'Shango', 'Shiva ', 'Shu', 'Sif', 'Sisifo', 'Sita ', 'Skadi', 'Sleipnir','Sobek', 'Surtr', 'Susanoo', 'Susanoo-no-Mikoto',
 'Tanatos', 'Tantalo', 'Tefnut', 'Teseo', 'Tezcatlipoca', 'Thor', 'Thoth', 'Tifon', 'Tlaloc', 'Tlazolteotl', 'Tonatiuh', 'Triton', 'Tsukuyomi', 'Tsukuyomi-no-Mikoto', 'Tyr', 'Ulises', 'Ullr', 'Urano', 'Valkirias', 'Varuna ', 'Vidar', 'Vishnu ', 'Woden', 'Xipe Totec', 'Xochiquetzal', 'Xolotl', 'Yama ', 'Yemoja', 'Ymir', 'Yum Kaax', 'Zeus', 'Ícaro'
]

catastrofesNaturales = [
    "Terremotos","Huracanes","Tsunamis","Inundaciones","Sequías","Erupciones volcánicas","Tormentas de nieve","Tornados","Incendios forestales","Avalanchas","Maremotos","Deslizamientos de tierra","Tormentas eléctricas","Ciclones","Granizadas severas","Ondas de calor","Tormentas de arena","Tormentas de granizo","Tormentas tropicales","Trombas marinas"
] 


 
def crear_usuario(animales, colores, comidas, coordenadas, herramientas, hijos, materiales, signos, war, dioses, catastrofesNaturales):
    usuario = {}
    for _ in range(2):  # Repetir el proceso dos veces
        categoria = random.choice([animales, colores, comidas, coordenadas, herramientas, hijos, materiales, signos, war, dioses, catastrofesNaturales])
        elemento = random.choice(categoria)
        usuario[categoria[0]] = elemento
    return usuario

usuario = crear_usuario(animales, colores, comidas, coordenadas, herramientas, hijos, materiales, signos, war, dioses, catastrofesNaturales)
print(usuario)