import { Metadata} from "next";
import Script from 'next/script'
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from './components/Navbar/Navbar';
import Footer from './components/Footer/Footer';
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import { SearchBarProvider } from './SearchBarContext';
import { AudioProvider } from './AudioContext';

config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Quienviene",
  description: "Generated by create next app",
};

 
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
       <body className={inter.className}>
       <AudioProvider>
        <SearchBarProvider>
            <Navbar/>
              {children}
            <Footer/>
          </SearchBarProvider>
        </AudioProvider>
       </body>
    </html>
  );
}