import { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from './components/Navbar/Navbar';
import Footer from './components/Footer/Footer';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Quienviene",
  description: "Generated by create next app",
};

 
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
       {/* <Script src="https://example.com/script.js" /> */}
       <body className={inter.className}>
        <Navbar/>
          {children}
        <Footer/>
       </body>
    </html>
  );
}