export default function RegionsForArgentina () {
 
    const regionsForArgentina = {
      'Ciudad Autónoma de Buenos Aires': [
        'Comuna 1',
        'Comuna 2',
        'Comuna 3',
        'Comuna 4',
        'Comuna 5',
        'Comuna 6',
        'Comuna 7',
        'Comuna 8',
        'Comuna 9',
        'Comuna 10',
        'Comuna 11',
        'Comuna 12',
        'Comuna 13',
        'Comuna 14',
        'Comuna 15'
    ],
    'Buenos Aires': [
    '25 de Mayo',
    '9 de Julio',
    'Adolfo Alsina',
    'Adolfo Gonzales Chaves',
    'Alberti',
    'Almirante Brown',
    'Arrecifes',
    'Avellaneda',
   'Ayacucho',
   'Azul',
   'Bahía Blanca',
   'Balcarce',
   'Baradero',
   'Benito Juárez',
   'Berazategui',
   'Berisso',
   'Bolívar',
   'Bragado',
   'Brandsen',
   'Campana',
   'Capitán Sarmiento',
   'Carlos Casares',
   'Carlos Tejedor',
   'Carmen de Areco',
   'Castelli',
   'Cañuelas',
   'Chacabuco',
   'Chascomús',
   'Chivilcoy',
   'Colón',
   'Coronel Dorrego',
   'Coronel Pringles',
   'Coronel Suárez',
   'Coronel de Marina Leonardo Rosales',
   'Daireaux',
   'Dolores',
   'Ensenada',
   'Escobar',
   'Esteban Echeverría',
   'Exaltación de la Cruz',
   'Ezeiza',
   'Florencio Varela',
   'Florentino Ameghino',
   'General Alvarado',
   'General Alvear',
   'General Arenales',
   'General Belgrano',
   'General Guido',
   'General Juan Madariaga',
   'General La Madrid',
   'General Las Heras',
   'General Lavalle',
    'General Paz',
    'General Pinto',
    'General Pueyrredón',
    'General Rodríguez',
    'General San Martín',
    'General Viamonte',
    'General Villegas',
    'Guaminí',
    'Hipólito Yrigoyen',
    'Hurlingham',
    'Ituzaingó',
    'José C. Paz',
    'Junín',
    'La Costa',
    'La Matanza',
    'La Plata',
    'Lanús',
    'Laprida',
    'Las Flores',
    'Leandro N. Alem',
    'Lezama',
    'Lincoln',
    'Lobería',
    'Lobos',
    'Lomas de Zamora',
    'Luján',
    'Magdalena',
    'Maipú',
    'Malvinas Argentinas',
    'Mar Chiquita',
    'Marcos Paz',
    'Mercedes',
    'Merlo',
    'Monte Hermoso',
    'Monte',
    'Moreno',
    'Morón',
    'Navarro',
    'Necochea',
    'Olavarría',
    'Patagones',
    'Pehuajó',
    'Pellegrini',
    'Pergamino',
    'Pila',
    'Pilar',
    'Pinamar',
    'Presidente Perón',
    'Punta Indio',
    'Puán',
    'Quilmes',
    'Ramallo',
    'Rauch',
    'Rivadavia',
    'Rojas',
    'Roque Pérez',
    'Saavedra',
    'Saladillo',
    'Salliqueló',
    'Salto',
    'San Andrés de Giles',
    'San Antonio de Areco',
    'San Cayetano',
    'San Fernando',
    'San Isidro',
    'San Miguel',
    'San Nicolás',
    'San Pedro',
    'San Vicente',
    'Suipacha',
    'Tandil',
    'Tapalqué',
    'Tigre',
    'Tordillo',
    'Tornquist',
    'Trenque Lauquen',
    'Tres Arroyos',
    'Tres Lomas',
    'Tres de Febrero',
    'Vicente López',
    'Villa Gesell',
    'Villarino',
    'Zárate'
  ],
        'Catamarca': [
          'Aconquija','Ancasti','Andalgalá','Antofagasta de la Sierra','Belén','Capayán','Corral Quemado','El Alto','El Rodeo','Fiambalá','Fray Mamerto Esquiú','Hualfin','Huillapima','Icaño','La Puerta','Las Juntas','Londres','Los Altos','Los Varela','Mutquin','Paclín','Pomán','Pozo de Piedra','Puerta de Corral Quemado','Puerta de San José','Recreo','San Fernando del Valle de Catamarca','San Fernando','San José','Santa María','Santa Rosa','Saujil','Tapso','Tinogasta','Valle Viejo','Villa Vil'
          ],
        'Chaco': [
          'Avia Terai','Barranqueras','Basail','Campo Largo','Capitán Solari','Charadai','Charata','Chorotis','Ciervo Petiso','Colonia Benítez','Colonia Elisa','Colonia Popular','Colonias Unidas','Concepción del Bermejo','Coronel Du Graty','Corzuela','Cote Lai','El Sauzalito','Enrique Urién','Fontana','Fuerte Esperanza','Gancedo','General Capdevila','General Pinedo','General San Martín','General Vedia','Hermoso Campo','Isla del Cerrito','Juan José Castelli','La Clotilde','La Eduvigis','La Escondida','La Leonesa','La Tigra','La Verde','Laguna Blanca','Laguna Limpia','Lapachito','Las Breñas','Las Garcitas','Las Palmas','Los Frentones','Machagai','Makallé','Margarita Belén','Miraflores','Misión Nueva Pompeya','Napenay',
          'Pampa Almirón','Pampa del Indio','Pampa del Infierno','Presidencia Roca','Presidencia Roque Sáenz Peña','Presidencia de la Plaza','Puerto Bermejo','Puerto Eva Perón','Puerto Tirol','Puerto Vilelas','Quitilipi','Resistencia','Samuhú','San Bernardo','Santa Sylvina','Taco Pozo','Tres Isletas','Villa Berthet','Villa Río Bermejito','Villa Ángela'
          ],
        'Chubut': [
          '28 de Julio','Aldea Beleiro','Aldea Epulef','Alto Río Senguer','Buen Pasto','Camarones','Carrenleufú','Cerro Centinela','Cholila','Colan Conhue','Comodoro Rivadavia','Corcovado','Cushamen','Dique Florentino Ameghino','Doctor Ricardo Rojas','Dolavon','Dr. Atilio Oscar Viglione','El Hoyo','El Maitén','Epuyén','Esquel','Facundo','Gaiman','Gan Gan','Gastre','Gobernador Costa','Gualjaina','José de San Martín','Lago Blanco','Lago Puelo','Lagunita Salada','Las Plumas','Los Altares','Paso de Indios','Paso del Sapo','Puerto Madryn','Puerto Pirámides','Rada Tilly','Rawson','Río Mayo','Río Pico','Sarmiento','Tecka','Telsen','Trelew','Trevelin'
          ],
        'Córdoba': [
            'Embalse',
            'La Cruz',
            'Los Cóndores',
            'Río de los Sauces',
            'Santa Rosa de Calamuchita',
            'Villa del Dique',
            'Villa General Belgrano',
            'San Agustín',
            'Villa Rumipal',
            'Villa Yacanto',
            'Córdoba',
            'Agua de Oro',
            'Colonia Caroya',
            'Colonia Tirolesa',
            'Estación General Paz',
            'Estación Juárez Celman',
            'Jesús María',
            'La Calera',
            'La Granja',
            'Malvinas Argentinas',
            'Mendiolaza',
            'Mi Granja',
            'Río Ceballos',
            'Saldán',
            'Salsipuedes',
            'Unquillo',
            'Villa Allende',
            'Cruz del Eje',
            'El Brete',
            'San Marcos Sierra',
            'Serrezuela',
            'Villa de Soto',
            'Buchardo',
            'Del Campillo',
            'Huinca Renancó',
            'Italó',
            'Jovita',
            'Mattaldi',
            'Villa Huidobro',
            'Villa Valeria',
            'Arroyo Algodón',
            'Arroyo Cabral',
            'Ausonia',
            'Chazón',
            'Etruria',
            'La Laguna',
            'La Palestina',
            'La Playosa',
            'Luca',
            'Pasco',
            'Silvio Pellico',
            'Ticino',
            'Tío Pujio',
            'Villa María',
            'Villa Nueva',
            'Deán Funes',
            'Quilino',
            'Alejandro Roca',
            'Bengolea',
            'Carnerillo',
            'Charras',
            'General Cabrera',
            'General Deheza',
            'Huanchilla',
            'La Carlota',
            'Los Cisnes',
            'Olaeta',
            'Reducción',
            'Santa Eufemia',
            'Ucacha',
            'Alejo Ledesma',
            'Arias',
            'Camilo Aldao',
            "Capitán General Bernardo O'Higgins",
            'Cavanagh',
            'Colonia Italiana',
            'Corral de Bustos Ifflinger',
            'Cruz Alta',
            'General Baldissera',
            'General Roca',
            'Guatimozín',
            'Inriville',
            'Isla Verde',
            'Leones',
            'Los Surgentes',
            'Marcos Juárez',
            'Monte Buey',
            'Saira',
            'San Carlos Minas',
            'Salsacate',
            'General Levalle',
            'La Cesira',
            'Laboulaye',
            'Melo',
            'Rosales',
            'Serrano',
            'Villa Rossi',
            'Bialet Massé',
            'Capilla del Monte',
            'Cosquín',
            'Huerta Grande',
            'La Cumbre',
            'La Falda',
            'Los Cocos',
            'San Antonio de Arredondo',
            'San Esteban',
            'Santa María de Punilla',
            'Tanti',
            'Valle Hermoso',
            'Villa Carlos Paz',
            'Villa Giardino',
            'Villa Río Icho Cruz',
            'Villa Santa Cruz del Lago',
            'Achiras',
            'Adelia María',
            'Alcira',
            'Alpa Corral',
            'Berrotarán',
            'Bulnes',
            'Chaján',
            'Coronel Baigorria',
            'Coronel Moldes',
            'Elena',
            'La Cautiva',
            'Las Acequias',
            'Las Higueras',
            'Las Vertientes',
            'Monte de los Gauchos',
            'Río Cuarto',
            'Sampacho',
            'San Basilio',
            'Santa Catalina Holmberg',
            'Tosquita',
            'Vicuña Mackenna',
            'La Para',
            'La Puerta',
            'Montecristo',
            'Obispo Trejo',
            'Piquillín',
            'Río Primero',
            'Villa Santa Rosa',
            'Villa Fontana',
            'Sebastián Elcano',
            'Villa de María',
            'Calchín',
            'Calchín Oeste',
            'Capilla del Carmen',
            'Carrilobo',
            'Colazo',
            'Costa Sacate',
            'Laguna Larga',
            'Las Junturas',
            'Luque',
            'Manfredi',
            'Matorrales',
            'Oncativo',
            'Pilar',
            'Pozo del Molle',
            'Río Segundo',
            'Santiago Temple',
            'Villa del Rosario',
            'Mina Clavero',
            'Nono',
            'San Pedro',
            'Villa Cura Brochero',
            'Villa Sarmiento',
            'La Paz',
            'Las Tapias',
            'Los Cerrillos',
            'San Javier y Yacanto',
            'San José',
            'Villa de las Rosas',
            'Villa Dolores',
            'Alicia',
            'Altos de Chipión',
            'Arroyito',
            'Balnearia',
            'Brinkmann',
            'Colonia Marina',
            'Colonia Prosperidad',
            'Colonia San Bartolomé',
            'Colonia Vignaud',
            'Devoto',
            'El Arañado',
            'El Fortín',
            'El Tío',
            'Freyre',
            'La Francia',
            'La Paquita',
            'La Tordilla',
            'Las Varas',
            'Las Varillas',
            'Marull',
            'Miramar de Ansenuza',
            'Morteros',
            'Porteña',
            'Quebracho Herrado',
            'Sacanta',
            'San Francisco',
            'Saturnino María Laspiur',
            'Seeber',
            'Tránsito',
            'Villa Concepción del Tío',
            'Alta Gracia',
            'Anisacate',
            'Bouwer',
            'Despeñaderos',
            'Lozada',
            'Malagueño',
            'Monte Ralo',
            'Toledo',
            'Villa Parque Santa Ana',
            'San Francisco del Chañar',
            'Almafuerte',
            'Colonia Almada',
            'Corralito',
            'Dalmacio Vélez',
            'Hernando',
            'James Craik',
            'Las Perdices',
            'Los Zorros',
            'Oliva',
            'Pampayasta Sud',
            'Río Tercero',
            'Tancacha',
            'Villa Ascasubi',
            'Cañada de Luque',
            'Las Peñas',
            'Sarmiento',
            'Sinsacate',
            'Villa del Totoral',
            'Las Arrias',
            'Lucio Victorio Mansilla',
            'San José de la Dormida',
            'San José de las Salinas',
            'San Pedro Norte',
            'Villa Tulumba',
            'Alto Alegre',
            'Ballesteros',
            'Ballesteros Sud',
            'Bell Ville',
            'Benjamín Gould',
            'Canals',
            'Chilibroste',
            'Cintra',
            'Colonia Bismarck',
            'Idiazábal',
            'Justiniano Posse',
            'Laborde',
            'Monte Leña',
            'Monte Maíz',
            'Morrison',
            'Noetinger',
            'Ordóñez',
            'Pascanas',
            'Pueblo Italiano',
            'San Antonio de Litín',
            'San Marcos Sud',
            'Viamonte',
            'Wenceslao Escalante',
            'Amboy',
            'Parque Calmayo',
            'Cañada del Sauce',
            'Las Bajadas',
            'Las Caleras',
            'Los Molinos',
            'Los Reartes',
            'Lutti',
            'San Ignacio',
            'Segunda Usina',
            'Villa Amancay',
            'Villa Ciudad Parque Los Reartes',
            'Villa Quillinzo',
            'Colonia Vicente Agüero',
            'El Manzano',
            'Villa Cerro Azul',
            'Alto de los Quebrachos',
            'Bañado de Soto',
            'Cruz de Caña',
            'Guanaco Muerto',
            'La Batea',
            'La Higuera',
            'Las Cañadas',
            'Las Playas',
            'Los Chañaritos',
            'Media Naranja',
            'Paso Viejo',
            'Tuclame',
            'Nicolás Bruzzone',
            'Onagoity',
            'Pincén',
            'Ranqueles',
            'Villa Sarmiento',
            'Avellaneda',
            'Cañada de Río Pinto',
            'Chuña',
            'Copacabana',
            'Los Pozos',
            'Olivares de San Nicolás',
            'Villa Gutiérrez',
            'Assunta',
            'El Rastreador',
            'Pacheco de Melo',
            'Paso del Durazno',
            'Colonia Barge',
            'Saladillo',
            'Villa Elisa',
            'Ciénaga del Coro',
            'El Chacho',
            'Estancia de Guadalupe',
            'Guasapampa',
            'La Playa',
            'Talaini',
            'Tosno',
            'Chancani',
            'Las Palmas',
            'Los Talares',
            'San Gerónimo',
            'Tala Cañada',
            'Villa de Pocho',
            'Leguizamón',
            'Río Bamba',
            'San Joaquín',
            'Cabalango',
            'Casa Grande',
            'Charbonier',
            'Cuesta Blanca',
            'Estancia Vieja',
            'Mayu Sumaj',
            'San Roque',
            'Tala Huasi',
            'Villa Parque Síquiman',
            'Chucul',
            'La Carolina El Potosí',
            'Las Albahacas',
            'Las Peñas Sud',
            'Malena',
            'Suco',
            'Villa El Chacay',
            'Washington',
            'Atahona',
            'Cañada de Machado',
            'Capilla de los Remedios',
            'Chalacea',
            'Colonia Las Cuatro Esquinas',
            'Comechingones',
            'Diego de Rojas',
            'El Crispín',
            'Esquina',
            'Kilómetro 658',
            'La Posta',
            'La Quinta',
            'Las Gramillas',
            'Las Saladas',
            'Maquinista Gallini',
            'Plaza de Mercedes',
            'Sagrada Familia',
            'Tinoco',
            'Cerro Colorado',
            'Chañar Viejo',
            'Eufrasio Loza',
            'Gutemberg',
            'La Rinconada',
            'Los Hoyos',
            'Puesto de Castro',
            'Rayo Cortado',
            'Santa Elena',
            'Villa Candelaria Norte',
            'Colonia Videla',
            'Impira',
            'Los Chañaritos',
            'Rincón',
            'Ambul',
            'Arroyo de los Patos',
            'Las Calles',
            'Las Rabonas',
            'Panaholma',
            'San Lorenzo',
            'San Vicente',
            'Sauce Arriba',
            'Conlara',
            'La Población',
            'Los Hornillos',
            'Luyaba',
            'Colonia Anita',
            'Colonia Iturraspe',
            'Colonia Las Pichanas',
            'Colonia San Pedro',
            'Colonia Valtelina',
            'Plaza Luxardo',
            'Toro Pujio',
            'Villa San Esteban',
            'Dique Chico',
            'Falda del Carmen',
            'La Cumbrecita',
            'La Paisanita',
            'La Rancherita','La Serranita',
            'Los Cedros',
            'Potrero de Garay',
            'Rafael García',
            'San Clemente',
            'Valle de Anisacate',
            'Villa Ciudad de América',
            'Villa del Prado',
            'Villa La Bolsa',
            'Villa Los Aromos',
            'Villa San Isidro',
            'Caminiaga',
            'Chuña Huasi',
            'Pozo Nuevo',
            'General Fotheringham',
            'Las Isletillas',
            'Pampayasta Norte',
            'Punta del Agua',
            'Candelaria Sud',
            'Capilla de Sitón',
            'La Pampa',
            'Los Mistoles',
            'Simbolar',
            'Churqui Cañada',
            'El Rodeo',
            'Rosario del Saladillo',
            'Aldea Santa María',
            'Ana Zumarán',
            'Colonia Bremen',
            'Villa Los Patos'
          ],
        'Corrientes': [
          '9 de Julio','Alvear','Bella Vista','Bonpland','Carolina','Cazadores Correntinos','Caá Catí','Cecilio Echavarría','Chavarría','Colonia Carlos Pellegrini','Colonia Libertad','Colonia Liebig','Colonia Pando','Colonia Santa Rosa','Concepción del Yaguareté Corá','Corrientes','Cruz de los Milagros','Curuzú Cuatiá','El Sombrero','Empedrado','Esquina','Estación Torrent','Felipe Yofré','Garaví','Garruchos','Gobernador Martínez','Gobernador Virasoro','Goya','Guaviraví','Herlitzka','Itatí','Ituzaingó','Itá Ibaté','Juan Pujol','La Cruz','Lavalle','Lomas de Vallejos','Loreto','Mariano I. Loza','Mburucuyá','Mercedes','Mocoretá','Monte Caseros','Pago de los Deseos','Palmar Grande','Parada Pucheta','Paso de la Patria','Paso de los Libres','Pedro R. Fernández','Perugorría','Pueblo Libertador','Ramada Paso','Riachuelo','Saladas','San Antonio Isla Apipé Grande','San Antonio de Itatí','San Carlos','San Cosme','San Isidro','San Lorenzo','San Luis del Palmar','San Miguel','San Roque','Santa Ana de los Guácaras','Santa Lucía','Santo Tomé','Sauce','Tabay','Tapebicuá','Tatacuá','Tres de Abril','Villa Olivari','Yapeyú','Yatay Ti Calle'
          ],
        'Entre Ríos': [
            '1º de Mayo','Alcaraz Norte','Alcaraz Sur','Alcaraz','Aldea Asunción','Aldea Brasilera','Aldea Eigenfeld','Aldea Grapschental','Aldea Protestante','Aldea Salto','Aldea San Antonio','Aldea San Antonio','Aldea San Juan','Aldea San Miguel','Aldea San Rafael','Aldea Santa María','Aldea Santa Rosa','Aldea Spatzenkutter','Aldea Valle María','Altamirano Sur','Antelo','Antonio Tomás','Arroyo Barú','Arroyo Burgos','Arroyo Cle','Arroyo Corralito','Arroyo Gená','Arroyo Las Tunas','Arroyo Maturrango','Arroyo Palo Seco','Arroyo del Medio','Banderas','Basavilbaso','Betbeder','Bovril','Caseros','Ceibas','Cerrito','Chajarí','Chilcas','Clodomiro Ledesma','Colonia Adivino','Colonia Alemana','Colonia Avellaneda','Colonia Avigdor','Colonia Ayuí','Colonia Baylina','Colonia Carrasco','Colonia Celina','Colonia Crespo','Colonia Elía','Colonia Ensayo','Colonia La Argentina','Colonia Merou','Colonia Oficial N° 13','Colonia Oficial Nº 3 y 14','Colonia Oficial Nº 5','Colonia San Anselmo y Aledañas','Colonia Santa María y Las Margaritas','Colonia Tunas','Colonia Viraró','Colón','Comuna Tala','Concepción del Uruguay','Concordia','Conscripto Bernardi','Costa Grande','Costa San Antonio','Costa Uruguay Norte','Costa Uruguay Sur','Crespo','Crucesitas Octava','Crucesitas Séptima','Crucesitas Tercera','Cuchilla Redonda','Diamante','Distrito Chañar','Distrito Chiqueros','Distrito Cuarto','Distrito Diego López','Distrito Pajonal','Distrito Primero','Distrito Quinto','Distrito Sauce','Distrito Tala','Distrito Talitas','Don Cristóbal I','Don Cristóbal II','Durazno','El Cimarrón','El Gramiyal','El Palenque','El Pingo','El Quebracho','El Redomón','El Solar','Enrique Carbó','Espinillo Norte','Estación Camps','Estación Escriña','Estación Lazo','Estación Parera','Estación Raíces','Estación Sosa','Estación Yeruá','Estación Yuquerí','Estancia Grande','Estaquitas','Febre','Federación','Federal','General Almada','General Alvear','General Campos','General Galarza','General Ramírez','General Roca','Gilbert','Gobernador Echagüe','Gobernador Etchevehere','Gobernador Mansilla','Gobernador Racedo','Gobernador Sola','González Calderón','Gualeguay','Gualeguaycito','Guardamonte','Hambis','Hasenkamp','Hernandarias','Herrera','Hinojal','Hocker','Ibicuy','Ingeniero Sajaroff','Irazusta','Isletas','Jubileo','Justo José de Urquiza','La Clarita','La Criolla','La Esmeralda','La Florida','La Fraternidad y Santa Juana','La Hierra','La Ollita','La Paz','La Picada','La Providencia','La Verbena','Laguna Benítez','Laguna del Pescado','Larroque','Las Cuevas','Las Garzas','Las Guachas','Las Mercedes','Las Moscas','Las Mulitas','Las Toscas','Laurencena','Loma Limpia','Los Charrúas','Los Conquistadores','Lucas González','Lucas Norte','Lucas Sur Primero','Lucas Sur Segundo','Líbaros','Maciá','Maria Luisa','María Grande 2º','María Grande','Mojones Norte','Mojones Sur','Molino Doll','Monte Redondo','Montoya','Mulas Grandes','Médanos','Nogoyá','Nueva Escocia','Nueva Vizcaya','Ombú','Oro Verde','Paraje Guayaquil','Paraje Las Tunas','Paraje Los Algarrobos','Paraná','Paso Duarte','Paso de La Laguna','Paso de la Arena','Paso de las Piedras','Pastor Britos','Pedernal','Perdices','Picada Berón','Piedras Blancas','Pronunciamiento','Pueblo Brugo','Pueblo Cazes','Pueblo General Belgrano','Pueblo Liebig','Puerto Algarrobo','Puerto Curtiembre','Puerto Yeruá','Punta del Monte','Quebracho','Raíces Oeste','Rincón de Nogoyá','Rincón del Cinto','Rincón del Doll','Rincón del Gato','Rocamora','Rosario del Tala','San Benito','San Cipriano','San Ernesto','San Gustavo','San Jaime de la Frontera','San José de Feliciano','San José de Gualeguaychú','San José','San Justo','San Justo','San Marcial','San Miguel','San Pedro','San Ramírez','San Ramón','San Roque','San Salvador','San Víctor','Santa Ana','Santa Anita','Santa Elena','Santa Lucía','Santa Luisa','Sauce Montrull','Sauce Pinto','Sauce Sur','Sauce de Luna','Saucecito','Seguí','Sir Leonard','Tabossi','Tezanos Pinto','Ubajay','Urdinarrain','Viale','Victoria','Villa Aranguren','Villa Clara','Villa Domínguez','Villa Elisa','Villa Fontana','Villa Libertador San Martín','Villa Mantero','Villa Paranacito','Villa Sabá Z. Hernández','Villa Urquiza','Villa del Rosario','Villaguay','Walter Moss','XX de Septiembre','Yacaré','Yeso Oeste','Ñancay',
          ],
        'Formosa': [
          'Buena Vista','Clorinda','Colonia Pastoril','Comandante Fontana','El Chorro','El Colorado','El Espinillo','Estanislao del Campo','Formosa','Fortín Lugones','General Lucio Victorio Mansilla','General Manuel Belgrano','Gran Guardia','Herradura','Ibarreta','Ingeniero Guillermo Nicasio Juárez','Laguna Blanca','Laguna Naick Neck','Laguna Yema','Las Lomitas','Los Chiriguanos','Mayor Villafañe','Misión San Francisco de Laishi','Misión Tacaaglé','Palo Santo','Pirané','Portón Negro','Pozo del Tigre','Riacho He He','San Hilario','San Martín Dos','Siete Palmas','Subteniente Perín','Tres Lagunas','Villa Dos Trece','Villa Escolar','Villa General Güemes',
          ],
        'Jujuy': [
          'Abdón Castro Tolay','Abra Pampa','Abralaite','Aguas Calientes','Arrayanal','Barrios','Caimancito','Calilegua','Cangrejillos','Caspalá','Catua','Cieneguillas','Coranzuli','Cusi Cusi','El Aguilar','El Carmen','El Cóndor','El Fuerte','El Moreno','El Piquete','El Talar','Fraile Pintado','Hipólito Yrigoyen','Huacalera','Humahuaca','La Esperanza','La Mendieta','La Quiaca','Libertador General San Martín','Maimará','Mina Pirquitas','Monterrico','Palca de Aparzo','Palma Sola','Palpalá','Pampa Blanca','Pampichuela','Perico','Puesto Viejo','Puesto del Marquez','Pumahuasi','Purmamarca','Rinconada','Rodeito','Rosario de Río Grande','San Antonio','San Francisco','San Pedro de Jujuy','San Salvador de Jujuy','Santa Ana','Santa Catalina','Santa Clara','Susques','Tilcara','Tres Cruces','Tumbaya','Uquia','Valle Grande','Vinalito','Volcán','Yala','Yavi','Yuto',
          ],
        'La Pampa': [
          'Abramo','Adolfo Van Praet','Agustoni','Algarrobo del Águila','Alpachiri','Alta Italia','Anguil','Arata','Ataliva Roca','Bernardo Larroudé','Bernasconi','Caleufú','Carro Quemado','Casa de Piedra','Catriló','Ceballos','Chacharramendi','Colonia 25 de Mayo','Colonia Barón','Colonia Santa María','Colonia Santa Teresa','Conhelo','Coronel Hilario Lagos','Cuchillo Co','Doblas','Dorila','Eduardo Castex','Embajador Martini','Falucho','General Acha','General Campos','General Pico','General San Martín','Gobernador Duval','Guatraché','Ingeniero Luiggi','Intendente Alvear','Jacinto Aráuz','La Adela','La Humada','La Maruja','La Reforma','Limay Mahuida','Lonquimay','Loventué','Luan Toro','Macachín','Maisonave','Mauricio Mayer','Metileo','Miguel Cané','Miguel Riglos','Monte Nievas','Parera','Perú','Pichi Huinca','Puelches','Puelén','Quehué','Quemú Quemú','Quetrequén','Rancul','Realicó','Relmo','Rolón','Rucanelo','Santa Isabel','Santa Rosa','Sarah','Speluzzi','Telén','Toay','Tomás M. Anchorena','Trenel','Unanué','Uriburu','Victorica','Villa Mirasol','Vértiz','Winifreda'
          ],
        'La Rioja': [
          'Arauco','Castro Barros','Chamical','Chilecito','Famatina','General Belgrano','General Felipe Varela','General Juan Facundo Quiroga','General Lamadrid','General Ortiz de Ocampo','General San Martín','Independencia','La Rioja','Rosario Vera Peñaloza','San Blas de Los Sauces','Sanagasta','Vinchina','Ángel Vicente Peñaloza'
          ],
        'Mendoza': [
          'General Alvear','Godoy Cruz','Guaymallén','Junín','La Paz','Las Heras','Lavalle','Luján de Cuyo','Maipú','Malargüe','Mendoza','Rivadavia','San Carlos','San Martín','San Rafael','Santa Rosa','Tunuyán','Tupungato'
          ],
        'Misiones': [
          '25 de Mayo','9 de Julio','Alba Posse','Almafuerte','Apóstoles','Aristóbulo del Valle','Arroyo del Medio','Azara','Bernardo de Irigoyen','Bonpland','Campo Grande','Campo Ramón','Campo Viera','Candelaria','Capioví','Caraguatay','Caá Yarí','Cerro Azul','Cerro Corá','Colonia Alberdi','Colonia Aurora','Colonia Delicia','Colonia Polana','Colonia Victoria','Colonia Wanda','Comandante Andresito','Concepción de la Sierra','Corpus Christi','Dos Arroyos','Dos de Mayo','El Alcázar','El Soberbio','Eldorado','Fachinal','Florentino Ameghino','Garuhapé','Garupá','General Alvear','General Urquiza','Gobernador López','Gobernador Roca','Guaraní','Hipólito Yrigoyen','Itacaruaré','Jardín América','Leandro N. Alem','Libertad','Loreto','Los Helechos','Mojón Grande','Montecarlo','Mártires','Oberá','Olegario V. Andrade','Panambí','Posadas','Pozo Azul','Profundidad','Puerto Esperanza','Puerto Iguazú','Puerto Leoni','Puerto Piray','Puerto Rico','Ruiz de Montoya','San Antonio','San Ignacio','San Javier','San José','San Martín','San Pedro','San Vicente','Santa Ana','Santa María','Santiago de Liniers','Santo Pipó','Tres Capones'
          ],
        'Neuquén': [
          'Aguada San Roque','Aluminé','Andacollo','Añelo','Bajada del Agrio','Barrancas','Buta Ranquil','Caviahue - Copahue','Centenario','Chorriaca','Chos Malal','Covunco Abajo','Coyuco - Cochico','Cutral Co','El Cholar','El Huecú','El Sauce','Guañacos','Huinganco','Junín de los Andes','Las Coloradas','Las Lajas','Las Ovejas','Loncopué','Los Catutos','Los Chihuidos','Los Miches','Manzano Amargo','Mariano Moreno','Neuquén','Octavio Pico','Paso Aguerre','Picún Leufú','Piedra del Águila','Pilo Lil','Plaza Huincul','Plottier','Quili Malal','Ramón M. Castro','Rincón de los Sauces','San Martín de los Andes','San Patricio del Chañar','Santo Tomás','Sauzal Bonito','Senillosa','Taquimilán','Tricao Malal','Varvarco - Invernada Vieja','Villa Curi Leuvú','Villa El Chocón','Villa La Angostura','Villa Pehuenia','Villa Puente Picún Leufú','Villa Traful','Villa del Nahueve','Vista Alegre','Zapala'
          ],
        'Río Negro': [
          'Allen','Campo Grande','Catriel','Cervantes','Chichinales','Chimpay','Choele Choel','Cinco Saltos','Cipolletti','Comallo','Contralmirante Cordero','Coronel Belisle','Darwin','Dina Huapi','El Bolsón','General Conesa','General Enrique Godoy','General Fernández Oro','General Roca','Guardia Mitre','Ingeniero Huergo','Ingeniero Jacobacci','Lamarque','Los Menucos','Luis Beltrán','Mainqué','Maquinchao','Ministro Ramos Mexía','Pilcaniyeu','Pomona','Río Colorado','San Antonio Oeste','San Carlos de Bariloche','Sierra Colorada','Sierra Grande','Valcheta','Viedma','Villa Regina','Ñorquinco'
          ],
        'Salta': [
          'Aguaray','Aguas Blancas','Angastaco','Animaná','Apolinario Saravia','Cachi','Cafayate','Campo Quijano','Campo Santo','Chicoana','Colonia Santa Rosa','Coronel Moldes','El Bordo','El Carril','El Galpón','El Jardín','El Potrero','El Quebrachal','El Tala','Embarcación','General Ballivián','General Güemes','General Mosconi','General Pizarro','Guachipas','Hipólito Yrigoyen','Iruya','Isla de Cañas','Joaquín V. González','La Caldera','La Candelaria','La Merced','La Poma','La Viña','Las Lajitas','Los Toldos','Molinos','Nazareno','Payogasta','Pichanal','Profesor Salvador Mazza','Rivadavia Banda Norte','Rivadavia Banda Sur','Rosario de Lerma','Rosario de la Frontera','Río Piedras','Salta','San Antonio de los Cobres','San Carlos','San José de Metán','San José de los Cerrillos','San Lorenzo','San Ramón de la Nueva Orán','Santa Victoria Este','Santa Victoria Oeste','Seclantás','Tartagal','Tolar Grande','Urundel','Vaqueros'
          ],
        'San Juan': [
          '25 de Mayo','9 de Julio','Albardón','Angaco','Calingasta','Caucete','Chimbas','Iglesia','Jáchal','Pocito','Rawson','Rivadavia','San Juan','San Martín','Santa Lucía','Sarmiento','Ullum','Valle Fértil','Zonda'
          ],
        'San Luis': [
          'Alto Pelado','Alto Pencoso','Anchorena','Arizona','Bagual','Balde','Batavia','Beazley','Buena Esperanza','Candelaria','Carpintería','Concarán','Cortaderas','Desaguadero','El Trapiche','El Volcán','Estancia Grande','Fortuna','Fortín El Patria','Fraga','Juan Jorba','Juan Llerena','Juana Koslay','Justo Daract','La Calera','La Carolina','La Punilla','La Punta','La Toma','La Vertiente','Lafinur','Las Aguadas','Las Chacras','Las Lagunas','Lavaisse','Leandro N. Alem','Los Manantiales','Los Molles','Luján','Nación Ranquel','Naschel','Navia','Nogolí','Nueva Galia','Papagayos','Paso Grande','Potrero de los Funes','Quines','Renca','Saladillo','San Francisco','San Jerónimo','San José del Morro','San Luis','San Martín','San Pablo','Santa Rosa','Talita','Tilisarao','Unión','Villa Larca','Villa Mercedes','Villa de Merlo','Villa de Praga','Villa de la Quebrada','Villa del Carmen','Zanjitas'
          ],
        'Santa Cruz': [
          'Caleta Olivia','Comandante Luis Piedrabuena','El Calafate','El Chaltén','Gobernador Gregores','Las Heras','Los Antiguos','Perito Moreno','Pico Truncado','Puerto San Julián','Puerto Santa Cruz','Río Gallegos','Río Turbio','Veintiocho de Noviembre'
        ],
        'Santa Fe':[
            'Aarón Castellanos','Acebal','Aguará Grande','Albarellos','Alcorta','Aldao','Alejandra','Alvear','Ambrosetti','Amenábar','Angeloni','Angélica','Arequito','Arminda','Armstrong','Arocena','Arroyo Aguiar','Arroyo Ceibal','Arroyo Leyes','Arroyo Seco','Arrufo','Arteaga','Ataliva','Aurelia','Avellaneda','Barrancas','Bauer y Sigel','Bella Italia','Berabevú','Berna','Bernardo de Irigoyen','Bigand','Bombal','Bouquet','Bustinza','Cabal','Cacique Ariacaiquín','Cafferata','Calchaquí','Campo Andino','Campo Piaggio','Candioti','Capitán Bermúdez','Capivara','Carcarañá','Carlos Pellegrini','Carmen del Sauce','Carmen','Carreras','Carrizales','Casalegno','Casas','Casilda','Castelar','Castellanos','Cavour','Cayastacito','Cayastá','Cañada Ombú','Cañada Rica','Cañada Rosquín','Cañada de Gómez','Cañada del Ucle','Centeno','Cepeda','Ceres','Chabas','Chapuy','Chañar Ladeado','Chovet','Christophersen','Classon','Colonia Aldao','Colonia Ana','Colonia Belgrano','Colonia Bicha','Colonia Bigand','Colonia Bossi','Colonia Cello','Colonia Clara','Colonia Dolores','Colonia Durán','Colonia Iturraspe','Colonia Margarita','Colonia Mascías','Colonia Maua','Colonia Raquel','Colonia Rosa','Constanza','Coronda','Coronel Arnold','Coronel Bogado','Coronel Domínguez','Coronel Fraga','Correa','Crispi','Cululú','Curupaity','Desvío Arijón','Diego de Alvear','Dos Rosas y La Legua','Díaz','Egusquiza','El Araza','El Rabón','El Sombrerito','El Trébol','Elisa','Elortondo','Emilia','Empalme San Carlos','Empalme Villa Constitución','Esmeralda','Esperanza','Estación Clucellas','Esteban Rams','Esther','Eusebia y Carolina','Eustolia','Felicia','Fidela','Fighiera','Firmat','Florencia','Fortín Olmos','Franck','Fray Luis Beltrán','Frontera','Fuentes','Funes','Gaboto','Galisteo','Garabato','Garibaldi','Gato Colorado','General Gelly','General Lagos','Gessler','Gobernador Crespo','Godoy','Golondrina','Granadero Baigorria','Gregoria Pérez de Denis','Grutly','Guadalupe Norte','Gálvez','Gödeken','Helvecia','Hersilia','Hipatía','Huanqueros','Hugentobler','Hughes','Humberto Primo','Humboldt','Ibarlucea','Ingeniero Chanourdie','Intiyaco','Irigoyen','Ituzaingó','Jacinto L. Aráuz','Josefina','Juan B. Molina','Juan de Garay','Juncal','La Brava','La Cabral','La Camila','La Chispa','La Criolla','La Gallareta','La Lucila','La Pelada','La Penca y Caraguatá','La Rubia','La Sarita','La Vanguardia','Labordeboy','Laguna Paiva','Landeta','Lanteri','Larrechea','Las Avispas','Las Bandurrias','Las Garzas','Las Palmeras','Las Parejas','Las Petacas','Las Rosas','Las Toscas','Las Tunas','Lazzarino','Lehmann','Llambí Campbell','Logroño','Loma Alta','Los Amores','Los Cardos','Los Laureles','Los Molinos','Los Quirquinchos','Los Tábanos','Lucio V. López','Luis Palacios','López','Maciel','Maggiolo','Malabrigo','Marcelino Escalada','Margarita','María Juana','María Luisa','María Susana','María Teresa','Matilde','Melincué','Miguel Torres','Moisés Ville','Monigotes','Monje','Monte Oscuridad','Monte Vera','Montefiore','Montes de Oca','Murphy','Máximo Paz','Naré','Nelson','Nicanor Molinas','Nuevo Torino','Oliveros','Palacios','Pavón Arriba','Pavón','Pedro Gómez Cello','Peyrano','Piamonte','Pilar','Piñero','Plaza Clucellas','Portugalete','Pozo Borrado','Presidente Roca','Progreso','Providencia','Pueblo Andino','Pueblo Esther','Pueblo Marini','Pueblo Muñoz','Puerto General San Martín','Pujato Norte','Pujato','Pérez','Rafaela','Ramayón','Ramona','Reconquista','Recreo','Ricardone','Rivadavia','Roldán','Romang','Rosario','Rueda','Rufino','Sa Pereyra','Saguier','Saladero Mariano Cabal','Salto Grande','San Agustín','San Antonio de Obligado','San Antonio','San Bernardo','San Bernardo','San Carlos Centro','San Carlos Norte','San Carlos Sud','San Cristóbal','San Eduardo','San Eugenio','San Fabián','San Francisco de Santa Fe','San Genaro','San Gregorio','San Guillermo','San Javier','San Jerónimo Norte','San Jerónimo Sud','San Jerónimo del Sauce','San Jorge','San José de la Esquina','San José del Rincón','San José','San Justo','San Lorenzo','San Mariano','San Martín Norte','San Martín de las Escobas','San Vicente','Sancti Spiritu','Sanford','Santa Clara de Buena Vista','Santa Clara de Saguier','Santa Fe','Santa Isabel','Santa Margarita','Santa María Centro','Santa María Norte','Santa Rosa de Calchines','Santa Teresa','Santo Domingo','Santo Tomé','Santurce','Sargento Cabral','Sarmiento','Sastre y Ortiz','Sauce Viejo','Serodino','Silva','Soldini','Soledad','Soutomayor','Suardi','Sunchales','Susana','Tacuarendi','Tacural','Tacurales','Tartagal','Teodelina','Theobald','Timbúes','Toba','Tortugas','Tostado','Totoras','Traill','Uranga','Venado Tuerto','Vera y Pintado','Vera','Videla','Vila','Villa Amelia','Villa Ana','Villa Cañás','Villa Constitución','Villa Eloísa','Villa Gobernador Gálvez','Villa Guillermina','Villa Minetti','Villa Mugueta','Villa Ocampo','Villa San José','Villa Saralegui','Villa Trinidad','Villada','Virginia','Wheelwright','Zavalla','Zenón Pereyra','Álvarez','Ñanducita'
          ],
          'Santiago del Estero': [
            'Añatuya','Bandera Beltrán','Campo Gallo','Clodomira','Colonia Dora','Fernández','Frías','Ingeniero Forres','La Banda','Loreto','Los Juríes','Los Telares','Monte Quemado','Nueva Esperanza','Pampa de los Guanacos','Pinto','Pozo Hondo','Quimilí','San Pedro de Guasayán','Santiago del Estero','Selva','Sumampa','Suncho Corral','Termas de Río Hondo','Tintina','Villa Atamisqui','Villa Ojo de Agua'   
          ],
        'Tierra del Fuego': [
          'Río Grande', 'Tolhuin','Ushuaia'
          ],
        'Tucumán': [
          '7 de Abril','Acheral','Agua Dulce y La Soledad','Aguilares','Alderetes','Alpachiri y El Molino','Alto Verde y Los Guchea','Amaicha del Valle','Amberes','Anca Juli','Arcadia','Atahona','Banda del Río Salí','Bella Vista','Benjamín Aráoz y El Tajamar','Buena Vista','Burruyacú','Capitán Cáceres','Cevil Redondo','Choromoro','Ciudacita','Colalao del Valle','Colombres','Concepción','Delfín Gallo','El Bracho y El Cevilar','El Cadillal','El Cercado','El Chañar','El Manantial','El Mojón','El Mollar','El Naranjito','El Naranjo y El Sunchal','El Polear y Los Córdoba','El Puestito','El Sacrificio','El Timbó','Escaba','Esquina y Mancopa','Estación Aráoz y Tacanas','Famaillá','Garmendia','Gastona y Belicha','Gobernador Piedrabuena','Graneros','Huasa Pampa','Juan Bautista Alberdi','La Cocha','La Esperanza','La Florida y Luisiana','La Ramada y La Cruz','La Trinidad','Lamadrid','Las Cejas','Las Talas','Las Talitas','León Rouges y Santa Rosa','Los Bulacio y Los Villagra','Los Gómez','Los Nogales','Los Pereyra','Los Puestos','Los Pérez','Los Ralos','Los Sarmiento y La Tipa','Los Sosa','Manuel García Fernández','Manuela Pedraza','Medina','Monte Bello','Monteagudo','Monteros','Pampa Mayo','Quilmes y Los Sueldos','Raco','Ranchillos y San Miguel','Rumi Punco','Río Chico y Nueva Trinidad','Río Colorado','Río Seco','San Andrés','San Felipe y Santa Bárbara','San Ignacio','San Isidro de Lules','San Javier','San José de la Cocha','San Miguel de Tucumán','San Pablo y Villa Nougués','San Pedro de Colalao','San Pedro y San Antonio','Santa Ana','Santa Cruz y La Tuna','Santa Lucía','Santa Rosa de Leales y Laguna Blanca','Sargento Moya','Simoca','Soldado Maldonado','Taco Ralo','Tafí Viejo','Tafí del Valle','Tapia','Teniente Berdina','Trancas','Villa Belgrano','Villa Chicligasta','Villa Padre Monti','Villa Quinteros','Villa de Leales','Yerba Buena','Yerba Buena','Yánima y El Corralito'
          ]
      };

    return regionsForArgentina
} 