export default function RegionsForArgentina () {
 
    const regionsForArgentina = {
        'Ciudad Autónoma de Buenos Aires':[
            'Comuna 3',  'Comuna 7',
            'Comuna 10', 'Comuna 11',
            'Comuna 15', 'Comuna 2',
            'Comuna 8',  'Comuna 6',
            'Comuna 9',  'Comuna 5',
            'Comuna 12', 'Comuna 13',
            'Comuna 1',  'Comuna 14',
            'Comuna 4'
          ],
        'Buenos Aires': [
                'General Alvarado',
                'Salliqueló',
                'General Paz',
                'Berazategui',
                'Almirante Brown',
                'General Pinto',
                'San Cayetano',
                'Tres Arroyos',
                'Coronel Dorrego',
                'Necochea',
                'Lezama',
                'Chascomús',
                'Punta Indio',
                'Campana',
                'Adolfo Alsina',
                'Puán',
                'General Villegas',
                'Presidente Perón',
                'La Plata',
                'Junín',
                'Brandsen',
                'Alberti',
                'Bragado',
                'Carlos Tejedor',
                '25 de Mayo',
                'Trenque Lauquen',
                'Esteban Echeverría',
                'Carmen de Areco',
                'Mercedes',
                'Hurlingham',
                'Morón',
                'Chacabuco',
                'Lanús',
                'Malvinas Argentinas',
                'General Las Heras',
                'Marcos Paz',
                'Tres Lomas',
                'General San Martín',
                'Lincoln',
                'Ituzaingó',
                'General Rodríguez',
                'Suipacha',
                'Tres de Febrero',
                'Chivilcoy',
                'Lomas de Zamora',
                'General Viamonte',
                'Colón',
                'Saavedra',
                'Monte Hermoso',
                'Lobería',
                'Berisso',
                'Tordillo',
                'San Fernando',
                'Zárate',
                'San Nicolás',
                'Florencio Varela',
                'Navarro',
                'Cañuelas',
                'San Vicente',
                'General Alvear',
                'Quilmes',
                'Pila',
                'General La Madrid',
                'Bolívar',
                'Balcarce',
                'Hipólito Yrigoyen',
                'Azul',
                'Dolores',
                'Daireaux',
                'Ayacucho',
                'Guaminí',
                'Laprida',
                'San Isidro',
                'Leandro N. Alem',
                'Patagones',
                'Coronel de Marina Leonardo Rosales',
                'Baradero',
                'San Pedro',
                'Rivadavia',
                'Florentino Ameghino',
                'Carlos Casares',
                'Benito Juárez',
                'Avellaneda',
                'Pellegrini',
                'Las Flores',
                'Rojas',
                'Escobar',
                'José C. Paz',
                'San Antonio de Areco',
                'Maipú',
                'Pinamar',
                'General Lavalle',
                'La Costa',
                'Magdalena',
                'Vicente López',
                'Pergamino',
                'Rauch',
                'Tandil',
                'Coronel Suárez',
                'Adolfo Gonzales Chaves',
                'Saladillo',             
                'Bahía Blanca',
                'Tigre',                 
                'Villarino',
                'Castelli',              
                'Moreno',
                'La Matanza',            
                'General Pueyrredón',
                'Mar Chiquita',          
                'Villa Gesell',
                'Tornquist',             
                'Coronel Pringles',
                'General Guido',         
                'General Juan Madariaga',
                'Ezeiza',                
                '9 de Julio',
                'Ramallo',               
                'General Belgrano',
                'Monte',                 
                'Roque Pérez',
                'Olavarría',             
                'Merlo',
                'Capitán Sarmiento',     
                'Salto',
                'Exaltación de la Cruz', 
                'San Miguel',
                'San Andrés de Giles',   
                'Pilar',
                'Luján',                 
                'Tapalqué',
                'Lobos',                 
                'General Arenales',
                'Pehuajó',               
                'Arrecifes',
                'Ensenada'
                
              ],
        'Catamarca': [
            'El Rodeo',
            'La Puerta',
            'Las Juntas',
            'Los Varela',
            'Ancasti',
            'Aconquija',
            'Andalgalá',
            'Antofagasta de la Sierra',
            'Belén',
            'Corral Quemado',
            'Hualfin',
            'Londres',
            'Pozo de Piedra',
            'Puerta de Corral Quemado',
            'Puerta de San José',
            'San Fernando',
            'Villa Vil',
            'Capayán',
            'Huillapima',
            'San Fernando del Valle de Catamarca',
            'El Alto',
            'Tapso',
            'Fray Mamerto Esquiú',
            'Icaño',
            'Recreo',
            'Paclín',
            'Mutquin',
            'Pomán',
            'Saujil',
            'San José',
            'Santa María',
            'Los Altos',
            'Santa Rosa',
            'Fiambalá',
            'Tinogasta',
            'Valle Viejo'
          ],
        'Chaco': [
            'Concepción del Bermejo',
            'Los Frentones',
            'Pampa del Infierno',
            'Taco Pozo',
            'General Vedia',
            'Isla del Cerrito',
            'La Leonesa',
            'Las Palmas',
            'Puerto Bermejo',
            'Puerto Eva Perón',
            'Presidencia Roque Sáenz Peña',
            'Charata',
            'Gancedo',
            'General Capdevila',
            'General Pinedo',
            'Hermoso Campo',
            'Chorotis',
            'Santa Sylvina',
            'Corzuela',
            'La Escondida',
            'Lapachito',
            'La Verde',
            'Makallé',
            'El Sauzalito',
            'Fuerte Esperanza',
            'Juan José Castelli',
            'Miraflores',
            'Misión Nueva Pompeya',
            'Villa Río Bermejito',
            'Avia Terai',
            'Campo Largo',
            'Napenay',
            'Colonia Popular',
            'Laguna Blanca',
            'Puerto Tirol',
            'Ciervo Petiso',
            'General San Martín',
            'La Eduvigis',
            'Laguna Limpia',
            'Pampa Almirón',
            'Pampa del Indio',
            'Presidencia Roca',
            'Tres Isletas',
            'Coronel Du Graty',
            'Enrique Urién',
            'Villa Ángela',
            'Las Breñas',
            'La Clotilde',
            'La Tigra',
            'San Bernardo',
            'Presidencia de la Plaza',
            'Colonia Benítez',
            'Margarita Belén',
            'Quitilipi',
            'Barranqueras',
            'Basail',
            'Fontana',
            'Puerto Vilelas',
            'Resistencia',
            'Samuhú',
            'Villa Berthet',
            'Capitán Solari',
            'Colonia Elisa',
            'Colonias Unidas',
            'Las Garcitas',
            'Cote Lai',
            'Charadai',
            'Machagai'
          ],
        'Chubut': [
            'Puerto Madryn',
            'Cholila',
            'El Hoyo',
            'El Maitén',
            'Epuyén',
            'Lago Puelo',
            'Comodoro Rivadavia',
            'Rada Tilly',
            'Camarones',
            'Corcovado',
            'Esquel',
            'Trevelin',
            'Dolavon',
            'Gaiman',
            'Tecka',
            'Rawson',
            'Trelew',
            'Alto Río Senguer',
            'Río Mayo',
            'Sarmiento',
            'Gobernador Costa',
            'José de San Martín',
            'Río Pico',
            'Gualjaina',
            '28 de Julio',
            'Paso de Indios',
            'Puerto Pirámides',
            'Cushamen',
            'Cerro Centinela',
            'Dique Florentino Ameghino',
            'Gastre',
            'Lagunita Salada',
            'Aldea Epulef',
            'Carrenleufú',
            'Colan Conhue',
            'Paso del Sapo',
            'Las Plumas',
            'Los Altares',
            'Aldea Beleiro',
            'Doctor Ricardo Rojas',
            'Facundo',
            'Lago Blanco',
            'Buen Pasto',
            'Gan Gan',
            'Telsen',
            'Dr. Atilio Oscar Viglione'
          ],
        'Córdoba': [
            'Embalse',
            'La Cruz',
            'Los Cóndores',
            'Río de los Sauces',
            'Santa Rosa de Calamuchita',
            'Villa del Dique',
            'Villa General Belgrano',
            'San Agustín',
            'Villa Rumipal',
            'Villa Yacanto',
            'Córdoba',
            'Agua de Oro',
            'Colonia Caroya',
            'Colonia Tirolesa',
            'Estación General Paz',
            'Estación Juárez Celman',
            'Jesús María',
            'La Calera',
            'La Granja',
            'Malvinas Argentinas',
            'Mendiolaza',
            'Mi Granja',
            'Río Ceballos',
            'Saldán',
            'Salsipuedes',
            'Unquillo',
            'Villa Allende',
            'Cruz del Eje',
            'El Brete',
            'San Marcos Sierra',
            'Serrezuela',
            'Villa de Soto',
            'Buchardo',
            'Del Campillo',
            'Huinca Renancó',
            'Italó',
            'Jovita',
            'Mattaldi',
            'Villa Huidobro',
            'Villa Valeria',
            'Arroyo Algodón',
            'Arroyo Cabral',
            'Ausonia',
            'Chazón',
            'Etruria',
            'La Laguna',
            'La Palestina',
            'La Playosa',
            'Luca',
            'Pasco',
            'Silvio Pellico',
            'Ticino',
            'Tío Pujio',
            'Villa María',
            'Villa Nueva',
            'Deán Funes',
            'Quilino',
            'Alejandro Roca',
            'Bengolea',
            'Carnerillo',
            'Charras',
            'General Cabrera',
            'General Deheza',
            'Huanchilla',
            'La Carlota',
            'Los Cisnes',
            'Olaeta',
            'Reducción',
            'Santa Eufemia',
            'Ucacha',
            'Alejo Ledesma',
            'Arias',
            'Camilo Aldao',
            "Capitán General Bernardo O'Higgins",
            'Cavanagh',
            'Colonia Italiana',
            'Corral de Bustos Ifflinger',
            'Cruz Alta',
            'General Baldissera',
            'General Roca',
            'Guatimozín',
            'Inriville',
            'Isla Verde',
            'Leones',
            'Los Surgentes',
            'Marcos Juárez',
            'Monte Buey',
            'Saira',
            'San Carlos Minas',
            'Salsacate',
            'General Levalle',
            'La Cesira',
            'Laboulaye',
            'Melo',
            'Rosales',
            'Serrano',
            'Villa Rossi',
            'Bialet Massé',
            'Capilla del Monte',
            'Cosquín',
            'Huerta Grande',
            'La Cumbre',
            'La Falda',
            'Los Cocos',
            'San Antonio de Arredondo',
            'San Esteban',
            'Santa María de Punilla',
            'Tanti',
            'Valle Hermoso',
            'Villa Carlos Paz',
            'Villa Giardino',
            'Villa Río Icho Cruz',
            'Villa Santa Cruz del Lago',
            'Achiras',
            'Adelia María',
            'Alcira',
            'Alpa Corral',
            'Berrotarán',
            'Bulnes',
            'Chaján',
            'Coronel Baigorria',
            'Coronel Moldes',
            'Elena',
            'La Cautiva',
            'Las Acequias',
            'Las Higueras',
            'Las Vertientes',
            'Monte de los Gauchos',
            'Río Cuarto',
            'Sampacho',
            'San Basilio',
            'Santa Catalina Holmberg',
            'Tosquita',
            'Vicuña Mackenna',
            'La Para',
            'La Puerta',
            'Montecristo',
            'Obispo Trejo',
            'Piquillín',
            'Río Primero',
            'Villa Santa Rosa',
            'Villa Fontana',
            'Sebastián Elcano',
            'Villa de María',
            'Calchín',
            'Calchín Oeste',
            'Capilla del Carmen',
            'Carrilobo',
            'Colazo',
            'Costa Sacate',
            'Laguna Larga',
            'Las Junturas',
            'Luque',
            'Manfredi',
            'Matorrales',
            'Oncativo',
            'Pilar',
            'Pozo del Molle',
            'Río Segundo',
            'Santiago Temple',
            'Villa del Rosario',
            'Mina Clavero',
            'Nono',
            'San Pedro',
            'Villa Cura Brochero',
            'Villa Sarmiento',
            'La Paz',
            'Las Tapias',
            'Los Cerrillos',
            'San Javier y Yacanto',
            'San José',
            'Villa de las Rosas',
            'Villa Dolores',
            'Alicia',
            'Altos de Chipión',
            'Arroyito',
            'Balnearia',
            'Brinkmann',
            'Colonia Marina',
            'Colonia Prosperidad',
            'Colonia San Bartolomé',
            'Colonia Vignaud',
            'Devoto',
            'El Arañado',
            'El Fortín',
            'El Tío',
            'Freyre',
            'La Francia',
            'La Paquita',
            'La Tordilla',
            'Las Varas',
            'Las Varillas',
            'Marull',
            'Miramar de Ansenuza',
            'Morteros',
            'Porteña',
            'Quebracho Herrado',
            'Sacanta',
            'San Francisco',
            'Saturnino María Laspiur',
            'Seeber',
            'Tránsito',
            'Villa Concepción del Tío',
            'Alta Gracia',
            'Anisacate',
            'Bouwer',
            'Despeñaderos',
            'Lozada',
            'Malagueño',
            'Monte Ralo',
            'Toledo',
            'Villa Parque Santa Ana',
            'San Francisco del Chañar',
            'Almafuerte',
            'Colonia Almada',
            'Corralito',
            'Dalmacio Vélez',
            'Hernando',
            'James Craik',
            'Las Perdices',
            'Los Zorros',
            'Oliva',
            'Pampayasta Sud',
            'Río Tercero',
            'Tancacha',
            'Villa Ascasubi',
            'Cañada de Luque',
            'Las Peñas',
            'Sarmiento',
            'Sinsacate',
            'Villa del Totoral',
            'Las Arrias',
            'Lucio Victorio Mansilla',
            'San José de la Dormida',
            'San José de las Salinas',
            'San Pedro Norte',
            'Villa Tulumba',
            'Alto Alegre',
            'Ballesteros',
            'Ballesteros Sud',
            'Bell Ville',
            'Benjamín Gould',
            'Canals',
            'Chilibroste',
            'Cintra',
            'Colonia Bismarck',
            'Idiazábal',
            'Justiniano Posse',
            'Laborde',
            'Monte Leña',
            'Monte Maíz',
            'Morrison',
            'Noetinger',
            'Ordóñez',
            'Pascanas',
            'Pueblo Italiano',
            'San Antonio de Litín',
            'San Marcos Sud',
            'Viamonte',
            'Wenceslao Escalante',
            'Amboy',
            'Parque Calmayo',
            'Cañada del Sauce',
            'Las Bajadas',
            'Las Caleras',
            'Los Molinos',
            'Los Reartes',
            'Lutti',
            'San Ignacio',
            'Segunda Usina',
            'Villa Amancay',
            'Villa Ciudad Parque Los Reartes',
            'Villa Quillinzo',
            'Colonia Vicente Agüero',
            'El Manzano',
            'Villa Cerro Azul',
            'Alto de los Quebrachos',
            'Bañado de Soto',
            'Cruz de Caña',
            'Guanaco Muerto',
            'La Batea',
            'La Higuera',
            'Las Cañadas',
            'Las Playas',
            'Los Chañaritos',
            'Media Naranja',
            'Paso Viejo',
            'Tuclame',
            'Nicolás Bruzzone',
            'Onagoity',
            'Pincén',
            'Ranqueles',
            'Villa Sarmiento',
            'Avellaneda',
            'Cañada de Río Pinto',
            'Chuña',
            'Copacabana',
            'Los Pozos',
            'Olivares de San Nicolás',
            'Villa Gutiérrez',
            'Assunta',
            'El Rastreador',
            'Pacheco de Melo',
            'Paso del Durazno',
            'Colonia Barge',
            'Saladillo',
            'Villa Elisa',
            'Ciénaga del Coro',
            'El Chacho',
            'Estancia de Guadalupe',
            'Guasapampa',
            'La Playa',
            'Talaini',
            'Tosno',
            'Chancani',
            'Las Palmas',
            'Los Talares',
            'San Gerónimo',
            'Tala Cañada',
            'Villa de Pocho',
            'Leguizamón',
            'Río Bamba',
            'San Joaquín',
            'Cabalango',
            'Casa Grande',
            'Charbonier',
            'Cuesta Blanca',
            'Estancia Vieja',
            'Mayu Sumaj',
            'San Roque',
            'Tala Huasi',
            'Villa Parque Síquiman',
            'Chucul',
            'La Carolina El Potosí',
            'Las Albahacas',
            'Las Peñas Sud',
            'Malena',
            'Suco',
            'Villa El Chacay',
            'Washington',
            'Atahona',
            'Cañada de Machado',
            'Capilla de los Remedios',
            'Chalacea',
            'Colonia Las Cuatro Esquinas',
            'Comechingones',
            'Diego de Rojas',
            'El Crispín',
            'Esquina',
            'Kilómetro 658',
            'La Posta',
            'La Quinta',
            'Las Gramillas',
            'Las Saladas',
            'Maquinista Gallini',
            'Plaza de Mercedes',
            'Sagrada Familia',
            'Tinoco',
            'Cerro Colorado',
            'Chañar Viejo',
            'Eufrasio Loza',
            'Gutemberg',
            'La Rinconada',
            'Los Hoyos',
            'Puesto de Castro',
            'Rayo Cortado',
            'Santa Elena',
            'Villa Candelaria Norte',
            'Colonia Videla',
            'Impira',
            'Los Chañaritos',
            'Rincón',
            'Ambul',
            'Arroyo de los Patos',
            'Las Calles',
            'Las Rabonas',
            'Panaholma',
            'San Lorenzo',
            'San Vicente',
            'Sauce Arriba',
            'Conlara',
            'La Población',
            'Los Hornillos',
            'Luyaba',
            'Colonia Anita',
            'Colonia Iturraspe',
            'Colonia Las Pichanas',
            'Colonia San Pedro',
            'Colonia Valtelina',
            'Plaza Luxardo',
            'Toro Pujio',
            'Villa San Esteban',
            'Dique Chico',
            'Falda del Carmen',
            'La Cumbrecita',
            'La Paisanita',
            'La Rancherita','La Serranita',
            'Los Cedros',
            'Potrero de Garay',
            'Rafael García',
            'San Clemente',
            'Valle de Anisacate',
            'Villa Ciudad de América',
            'Villa del Prado',
            'Villa La Bolsa',
            'Villa Los Aromos',
            'Villa San Isidro',
            'Caminiaga',
            'Chuña Huasi',
            'Pozo Nuevo',
            'General Fotheringham',
            'Las Isletillas',
            'Pampayasta Norte',
            'Punta del Agua',
            'Candelaria Sud',
            'Capilla de Sitón',
            'La Pampa',
            'Los Mistoles',
            'Simbolar',
            'Churqui Cañada',
            'El Rodeo',
            'Rosario del Saladillo',
            'Aldea Santa María',
            'Ana Zumarán',
            'Colonia Bremen',
            'Villa Los Patos'
          ],
        'Corrientes': [
            'Bella Vista',
            'Tres de Abril',
            'San Antonio de Itatí',
            'Corrientes',
            'Riachuelo',
            'Colonia Santa Rosa',
            'Concepción del Yaguareté Corá',
            'Tabay',
            'Tatacuá',
            'Cazadores Correntinos',
            'Curuzú Cuatiá',
            'Perugorría',
            'El Sombrero',
            'Empedrado',
            'Esquina',
            'Pueblo Libertador',
            'Alvear',
            'Estación Torrent',
            'Caá Catí',
            'Itá Ibaté',
            'Lomas de Vallejos',
            'Palmar Grande',
            'Carolina',
            'Goya',
            'San Isidro',
            'Itatí',
            'Ramada Paso',
            'Colonia Liebig',
            'Ituzaingó',
            'San Antonio Isla Apipé Grande',
            'San Carlos',
            'Villa Olivari',
            'Cecilio Echavarría',
            'Cruz de los Milagros',
            'Gobernador Martínez',
            'Lavalle',
            'Santa Lucía',
            'Yatay Ti Calle',
            'Mburucuyá',
            'Felipe Yofré',
            'Mariano I. Loza',
            'Mercedes',
            'Colonia Libertad',
            'Juan Pujol',
            'Mocoretá',
            'Monte Caseros',
            'Bonpland',
            'Parada Pucheta',
            'Paso de los Libres',
            'Tapebicuá',
            'Saladas',
            'San Lorenzo',
            'Pago de los Deseos',
            'Paso de la Patria',
            'San Cosme',
            'Santa Ana de los Guácaras',
            'Herlitzka',
            'San Luis del Palmar',
            'Colonia Carlos Pellegrini',
            'Guaviraví',
            'La Cruz',
            'Yapeyú',
            'Loreto',
            'San Miguel',
            '9 de Julio',
            'Pedro R. Fernández',
            'Chavarría',
            'Colonia Pando',
            'San Roque',
            'Garruchos',
            'Gobernador Virasoro',
            'Garaví',
            'Santo Tomé',
            'Sauce'
          ],
        'Entre Ríos': [
            'Colón',
            'San José',
            'Ubajay',
            'Villa Elisa',
            'Colonia Ayuí',
            'Concordia',
            'Estancia Grande',
            'La Criolla',
            'Los Charrúas',
            'Puerto Yeruá',
            'Aldea Valle María',
            'Diamante',
            'General Ramírez',
            'Villa Libertador San Martín',
            'Chajarí',
            'Federación',
            'Los Conquistadores',
            'San Jaime de la Frontera',
            'Santa Ana',
            'Villa del Rosario',
            'Conscripto Bernardi',
            'Federal',
            'Sauce de Luna',
            'San José de Feliciano',
            'General Galarza',
            'Gualeguay',
            'Aldea San Antonio',
            'Enrique Carbó',
            'Gilbert',
            'San José de Gualeguaychú',
            'Larroque',
            'Pueblo General Belgrano',
            'Urdinarrain',
            'Ceibas',
            'Ibicuy',
            'Villa Paranacito',
            'Alcaraz',
            'Bovril',
            'La Paz',
            'Piedras Blancas',
            'San Gustavo',
            'Santa Elena',
            'Villa Aranguren',
            'Villa Sabá Z. Hernández',
            'Lucas González',
            'Nogoyá',
            'Cerrito',
            'Colonia Avellaneda',
            'Crespo',
            'Hasenkamp',
            'Hernandarias',
            'María Grande',
            'Oro Verde',
            'Paraná',
            'San Benito',
            'Seguí',
            'Tabossi',
            'Viale',
            'Villa Urquiza',
            'General Campos',
            'San Salvador',
            'Gobernador Mansilla',
            'Maciá',
            'Rosario del Tala',
            'Basavilbaso',
            'Caseros',
            'Colonia Elía',
            'Concepción del Uruguay',
            'Herrera',
            '1º de Mayo',
            'Pronunciamiento',
            'San Justo',
            'Santa Anita',
            'Villa Mantero',
            'Victoria',
            'Villa Clara',
            'Villa Domínguez',
            'Villaguay',
            'Arroyo Barú',
            'La Clarita',
            'Pueblo Cazes',
            'General Roca',
            'Nueva Escocia',
            'Pedernal',
            'Aldea Protestante',
            'Aldea Spatzenkutter',
            'Colonia Ensayo',
            'Gobernador Racedo',
            'Las Cuevas',
            'El Cimarrón',
            'Nueva Vizcaya',
            'San Víctor',
            'Aldea Asunción',
            'Aldea San Juan',
            'Estación Parera',
            'Irazusta',
            'Colonia Avigdor',
            'El Solar',
            'Ombú',
            'Don Cristóbal II',
  'Febre',
  'XX de Septiembre',
  'Aldea Santa María',
  'Aldea Santa Rosa',
  'Colonia Crespo',
  'El Palenque',
  'Estación Sosa',
  'Gobernador Etchevehere',
  'La Picada',
  'Las Garzas',
  'Paraje Las Tunas',
  'Puerto Curtiembre',
  'Sauce Montrull',
  'Sauce Pinto',
  'Tezanos Pinto',
  'Villa Fontana',
  'Durazno',
  'Gobernador Echagüe',
  'Gobernador Sola',
  'Guardamonte',
  'Comuna Tala',
  'Las Moscas',
  'Líbaros',
  'Rocamora',
  'San Cipriano',
  'San Marcial',
  'Antelo',
  'Rincón de Nogoyá',
  'Rincón del Doll',
  'Ingeniero Sajaroff',
  'Jubileo',
  'Paso de La Laguna',
  'San Miguel',
  'Colonia San Anselmo y Aledañas',
  'Hambis',
  'Hocker',
  'Pueblo Liebig',
  'Clodomiro Ledesma',
  'El Redomón',
  'Estación Yeruá',
  'Estación Yuquerí',
  'San Justo',
  'Aldea Brasilera',
  'Aldea Grapschental',
  'Aldea Salto',
  'Costa Grande',
  'Estación Camps',
  'General Alvear',
  'Isletas',
  'Colonia Alemana',
  'Colonia La Argentina',
  'Colonia Santa María y Las Margaritas',
  'Colonia Tunas',
  'Gualeguaycito',
  'La Florida',
  'La Fraternidad y Santa Juana',
  'Paraje Guayaquil',
  'San Pedro',
  'San Ramón',
  'San Roque',
  'Arroyo del Medio',
  'Arroyo Las Tunas',
  'Banderas',
  'Distrito Diego López',
  'El Gramiyal',
  'Loma Limpia',
  'Paso Duarte',
  'Santa Lucía',
  'Distrito Chañar',
  'La Esmeralda',
  'La Hierra',
  'La Verbena',
  'Laguna Benítez',
  'Las Mulitas',
  'Mulas Grandes',
  'Distrito Cuarto',
  'Distrito Primero',
  'Distrito Quinto',
  'Estación Lazo',
  'González Calderón',
  'Monte Redondo',
  'Punta del Monte',
  'Costa San Antonio',
  'Costa Uruguay Norte',
  'Costa Uruguay Sur',
  'Cuchilla Redonda',
  'Distrito Talitas',
  'Estación Escriña',
  'General Almada',
  'Las Mercedes',
  'Pastor Britos',
  'Perdices',
  'Rincón del Cinto',
  'Rincón del Gato',
  'Médanos',
  'Ñancay',
  'Alcaraz Norte',
  'Alcaraz Sur',
  'Colonia Carrasco',
  'Colonia Oficial N° 13',
  'Colonia Oficial Nº 3 y 14',
  'Colonia Viraró',
  'El Quebracho',
  'Estaquitas',
  'La Providencia',
  'Las Toscas',
  'Picada Berón',
  'Puerto Algarrobo',
  'San Ramírez',
  'Saucecito',
  'Sir Leonard',
  'Yacaré',
  'Yeso Oeste',
  'Aldea San Miguel',
  'Betbeder',
  'Crucesitas Octava',
  'Crucesitas Séptima',
  'Crucesitas Tercera',
  'Distrito Chiqueros',
  'Distrito Sauce',
  'Don Cristóbal I',
  'Justo José de Urquiza',
  'Laurencena',
  'Aldea Eigenfeld',
  'Maria Luisa',
  'Aldea San Antonio',
  'Aldea San Rafael',
  'Antonio Tomás',
  'Arroyo Burgos',
  'Arroyo Corralito',
  'Arroyo Maturrango',
  'Arroyo Palo Seco',
  'Colonia Celina',
  'Colonia Merou',
  'Distrito Tala',
  'El Pingo',
  'Espinillo Norte',
  'María Grande 2º',
  'Paso de la Arena',
  'Paso de las Piedras',
  'Pueblo Brugo',
  'Quebracho',
  'Santa Luisa',
  'Colonia Baylina',
  'Colonia Oficial Nº 5',
  'San Ernesto',
  'Walter Moss',
  'Altamirano Sur',
  'Arroyo Cle',
  'La Ollita',
  'Las Guachas',
  'Sauce Sur',
  'Arroyo Gená',
  'Chilcas',
  'Distrito Pajonal',
  'Hinojal',
  'Laguna del Pescado',
  'Molino Doll',
  'Montoya',
  'Colonia Adivino',
  'Estación Raíces',
  'Lucas Norte',
  'Lucas Sur Primero',
  'Lucas Sur Segundo',
  'Mojones Norte',
  'Mojones Sur',
  'Paraje Los Algarrobos',
  'Raíces Oeste'
          ],
        'Formosa': [
            'Laguna Yema',
            'Formosa',
            'General Lucio Victorio Mansilla',
            'Herradura',
            'Misión San Francisco de Laishi',
            'Villa Escolar',
            'Ingeniero Guillermo Nicasio Juárez',
            'Comandante Fontana',
            'Estanislao del Campo',
            'General Manuel Belgrano',
            'Villa General Güemes',
            'Ibarreta',
            'Las Lomitas',
            'Pozo del Tigre',
            'San Martín Dos',
            'El Espinillo',
            'Misión Tacaaglé',
            'Clorinda',
            'Laguna Blanca',
            'Laguna Naick Neck',
            'Riacho He He',
            'El Colorado',
            'Mayor Villafañe',
            'Palo Santo',
            'Pirané',
            'Villa Dos Trece',
            'El Chorro',
            'Los Chiriguanos',
            'Colonia Pastoril',
            'Gran Guardia',
            'San Hilario',
            'Fortín Lugones',
            'Subteniente Perín',
            'Buena Vista',
            'Tres Lagunas',
            'Siete Palmas',
            'Portón Negro'
          ],
        'Jujuy': [
            'Abra Pampa',
            'San Salvador de Jujuy',
            'Yala',
            'Aguas Calientes',
            'El Carmen',
            'Monterrico',
            'Pampa Blanca',
            'Puesto Viejo',
            'Perico',
            'El Aguilar',
            'Humahuaca',
            'Caimancito',
            'Calilegua',
            'Fraile Pintado',
            'Libertador General San Martín',
            'Yuto',
            'Palpalá',
            'San Antonio',
            'La Esperanza',
            'La Mendieta',
            'San Pedro de Jujuy',
            'El Talar',
            'Palma Sola',
            'Santa Clara',
            'Maimará',
            'Tilcara',
            'La Quiaca',
            'Abdón Castro Tolay',
            'Abralaite',
            'Puesto del Marquez',
            'Hipólito Yrigoyen',
            'Palca de Aparzo',
            'Tres Cruces',
            'Uquia',
            'Mina Pirquitas',
            'Rinconada',
            'Arrayanal',
            'El Fuerte',
            'Rodeito',
            'Rosario de Río Grande',
            'El Piquete',
            'Vinalito',
            'Cieneguillas',
            'Cusi Cusi',
            'Santa Catalina',
            'Catua',
            'Coranzuli',
            'Susques',
            'Huacalera',
            'El Moreno',
            'Purmamarca',
            'Tumbaya',
            'Volcán',
            'Caspalá',
            'Pampichuela',
            'San Francisco',
            'Santa Ana',
            'Valle Grande',
            'Barrios',
            'Cangrejillos',
            'El Cóndor',
            'Pumahuasi',
            'Yavi'
          ],
        'La Pampa': [
            'Abramo',                'Algarrobo del Águila', 'Alpachiri',
            'Alta Italia',           'Anguil',               'Arata',
            'Ataliva Roca',          'Bernardo Larroudé',    'Bernasconi',
            'Caleufú',               'Carro Quemado',        'Catriló',
            'Ceballos',              'Colonia Barón',        'Conhelo',
            'Coronel Hilario Lagos', 'Doblas',               'Dorila',
            'Eduardo Castex',        'Embajador Martini',    'General Acha',
            'General Campos',        'General Pico',         'General San Martín',
            'Gobernador Duval',      'Guatraché',            'Ingeniero Luiggi',
            'Intendente Alvear',     'Jacinto Aráuz',        'La Adela',
            'La Humada',             'La Maruja',            'Lonquimay',
            'Luan Toro',             'Macachín',             'Mauricio Mayer',
            'Metileo',               'Miguel Cané',          'Miguel Riglos',
            'Monte Nievas',          'Parera',               'Puelches',
            'Puelén',                'Quehué',               'Quemú Quemú',
            'Rancul',                'Realicó',              'Rolón',
            'Santa Isabel',          'Santa Rosa',           'Colonia Santa Teresa',
            'Telén',                 'Toay',                 'Tomás M. Anchorena',
            'Trenel',                'Uriburu',              'Colonia 25 de Mayo',
            'Vértiz',                'Victorica',            'Villa Mirasol',
            'Winifreda',             'Casa de Piedra',       'Adolfo Van Praet',
            'Agustoni',              'Colonia Santa María',  'Cuchillo Co',
            'Chacharramendi',        'Falucho',              'La Reforma',
            'Limay Mahuida',         'Loventué',             'Maisonave',
            'Perú',                  'Pichi Huinca',         'Quetrequén',
            'Relmo',                 'Rucanelo',             'Sarah',
            'Speluzzi',              'Unanué'
          ],
        'La Rioja': [
            'Arauco',
            'La Rioja',
            'Castro Barros',
            'General Felipe Varela',
            'Chamical',
            'Chilecito',
            'Famatina',
            'Ángel Vicente Peñaloza',
            'General Belgrano',
            'General Juan Facundo Quiroga',
            'General Lamadrid',
            'General Ortiz de Ocampo',
            'General San Martín',
            'Vinchina',
            'Independencia',
            'Rosario Vera Peñaloza',
            'San Blas de Los Sauces',
            'Sanagasta'
          ],
        'Mendoza': [
            'Mendoza',       'General Alvear',
            'Godoy Cruz',    'Guaymallén',
            'Junín',         'La Paz',
            'Las Heras',     'Lavalle',
            'Luján de Cuyo', 'Maipú',
            'Malargüe',      'Rivadavia',
            'San Carlos',    'San Martín',
            'San Rafael',    'Santa Rosa',
            'Tunuyán',       'Tupungato'
          ],
        'Misiones': [
            'Apóstoles',
            'Azara',
            'San José',
            'Tres Capones',
            'Aristóbulo del Valle',
            'Campo Grande',
            'Dos de Mayo',
            'Bonpland',
            'Candelaria',
            'Cerro Corá',
            'Loreto',
            'Mártires',
            'Profundidad',
            'Santa Ana',
            'Fachinal',
            'Garupá',
            'Posadas',
            'Concepción de la Sierra',
            'Santa María',
            'Colonia Delicia',
            'Colonia Victoria',
            'Eldorado',
            '9 de Julio',
            'Santiago de Liniers',
            'Bernardo de Irigoyen',
            'Comandante Andresito',
            'San Antonio',
            'El Soberbio',
            'San Vicente',
            'Puerto Esperanza',
            'Puerto Iguazú',
            'Libertad',
            'Colonia Wanda',
            'Almafuerte',
            'Arroyo del Medio',
            'Caá Yarí',
            'Cerro Azul',
            'Dos Arroyos',
            'Gobernador López',
            'Leandro N. Alem',
            'Olegario V. Andrade',
            'Capioví',
            'El Alcázar',
            'Garuhapé',
            'Puerto Leoni',
            'Puerto Rico',
            'Ruiz de Montoya',
            'Caraguatay',
            'Montecarlo',
            'Puerto Piray',
            'Campo Ramón',
            'Campo Viera',
            'Colonia Alberdi',
            'General Alvear',
            'Guaraní',
            'Los Helechos',
            'Oberá',
            'Panambí',
            'San Martín',
            'Colonia Polana',
            'Corpus Christi',
            'General Urquiza',
            'Gobernador Roca',
            'Hipólito Yrigoyen',
            'Jardín América',
            'San Ignacio',
            'Santo Pipó',
            'Florentino Ameghino',
            'Itacaruaré',
            'Mojón Grande',
            'San Javier',
            'Pozo Azul',
            'San Pedro',
            'Alba Posse',
            'Colonia Aurora',
            '25 de Mayo'
          ],
        'Neuquén': [
            'Aluminé',
            'Añelo',
            'San Patricio del Chañar',
            'Las Coloradas',
            'Piedra del Águila',
            'Centenario',
            'Cutral Co',
            'Neuquén',
            'Plaza Huincul',
            'Plottier',
            'Senillosa',
            'Villa El Chocón',
            'Vista Alegre',
            'Chos Malal',
            'Tricao Malal',
            'Junín de los Andes',
            'San Martín de los Andes',
            'Loncopué',
            'Villa La Angostura',
            'Andacollo',
            'Huinganco',
            'Las Ovejas',
            'Los Miches',
            'Caviahue - Copahue',
            'El Cholar',
            'El Huecú',
            'Taquimilán',
            'Barrancas',
            'Buta Ranquil',
            'Rincón de los Sauces',
            'Picún Leufú',
            'Bajada del Agrio',
            'Las Lajas',
            'Mariano Moreno',
            'Zapala',
            'Villa Pehuenia',
            'Aguada San Roque',
            'Los Chihuidos',
            'Pilo Lil',
            'Santo Tomás',
            'Sauzal Bonito',
            'Coyuco - Cochico',
            'Villa Curi Leuvú',
            'Chorriaca',
            'Villa Traful',
            'Guañacos',
            'Manzano Amargo',
            'Varvarco - Invernada Vieja',
            'Villa del Nahueve',
            'Octavio Pico',
            'El Sauce',
            'Paso Aguerre',
            'Quili Malal',
            'Covunco Abajo',
            'Los Catutos',
            'Ramón M. Castro',
            'Villa Puente Picún Leufú'
          ],
        'Río Negro': [
            'Guardia Mitre',
            'Viedma',
            'Chimpay',
            'Choele Choel',
            'Coronel Belisle',
            'Darwin',
            'Lamarque',
            'Luis Beltrán',
            'Pomona',
            'El Bolsón',
            'San Carlos de Bariloche',
            'General Conesa',
            'Allen',
            'Campo Grande',
            'Catriel',
            'Cervantes',
            'Chichinales',
            'Cinco Saltos',
            'Cipolletti',
            'Contralmirante Cordero',
            'General Enrique Godoy',
            'General Fernández Oro',
            'General Roca',
            'Ingeniero Huergo',
            'Mainqué',
            'Villa Regina',
            'Ministro Ramos Mexía',
            'Sierra Colorada',
            'Ñorquinco',
            'Río Colorado',
            'Comallo',
            'Pilcaniyeu',
            'San Antonio Oeste',
            'Sierra Grande',
            'Valcheta',
            'Ingeniero Jacobacci',
            'Los Menucos',
            'Maquinchao',
            'Dina Huapi'
          ],
        'Salta': [
            'Apolinario Saravia',
            'El Quebrachal',
            'General Pizarro',
            'Joaquín V. González',
            'Las Lajitas',
            'Cachi',
            'Payogasta',
            'Cafayate',
            'Salta',
            'San Lorenzo',
            'San José de los Cerrillos',
            'La Merced',
            'Chicoana',
            'El Carril',
            'Campo Santo',
            'El Bordo',
            'General Güemes',
            'Aguaray',
            'Embarcación',
            'General Ballivián',
            'General Mosconi',
            'Profesor Salvador Mazza',
            'Tartagal',
            'Guachipas',
            'Iruya',
            'Isla de Cañas',
            'La Caldera',
            'Vaqueros',
            'El Jardín',
            'El Tala',
            'La Candelaria',
            'La Poma',
            'Coronel Moldes',
            'La Viña',
            'San Antonio de los Cobres',
            'Tolar Grande',
            'El Galpón',
            'San José de Metán',
            'Molinos',
            'Río Piedras',
            'Seclantás',
            'Aguas Blancas',
            'Colonia Santa Rosa',
            'Hipólito Yrigoyen',
            'Pichanal',
            'San Ramón de la Nueva Orán',
            'Urundel',
            'Rivadavia Banda Norte',
            'Rivadavia Banda Sur',
            'Santa Victoria Este',
            'El Potrero',
            'Rosario de la Frontera',
            'Campo Quijano',
            'Rosario de Lerma',
            'Angastaco',
            'Animaná',
            'San Carlos',
            'Los Toldos',
            'Nazareno',
            'Santa Victoria Oeste'
          ],
        'San Juan': [
            'Albardón',     'Angaco',
            'Calingasta',   'San Juan',
            'Caucete',      'Chimbas',
            'Iglesia',      'Jáchal',
            '9 de Julio',   'Pocito',
            'Rawson',       'Rivadavia',
            'San Martín',   'Santa Lucía',
            'Sarmiento',    'Ullum',
            'Valle Fértil', '25 de Mayo',
            'Zonda'
          ],
        'San Luis': [
            'Candelaria',         'Luján',            'Quines',
            'San Francisco',      'Los Manantiales',  'Estancia Grande',
            'El Trapiche',        'La Toma',          'Concarán',
            'Naschel',            'Tilisarao',        'Justo Daract',
            'Nación Ranquel',     'Villa Mercedes',   'Buena Esperanza',
            'Unión',              'Carpintería',      'Santa Rosa',
            'Villa de Merlo',     'Desaguadero',      'El Volcán',
            'Juana Koslay',       'La Punta',         'Potrero de los Funes',
            'San Luis',           'San Martín',       'Leandro N. Alem',
            'La Calera',          'Nogolí',           'Villa de la Quebrada',
            'La Carolina',        'Fraga',            'Saladillo',
            'Cortaderas',         'Papagayos',        'Renca',
            'San Pablo',          'Villa del Carmen', 'Villa Larca',
            'San José del Morro', 'Juan Jorba',       'Juan Llerena',
            'La Punilla',         'Lavaisse',         'Anchorena',
            'Arizona',            'Bagual',           'Batavia',
            'Fortín El Patria',   'Fortuna',          'Navia',
            'Nueva Galia',        'Lafinur',          'Los Molles',
            'Talita',             'Alto Pelado',      'Alto Pencoso',
            'Balde',              'Beazley',          'San Jerónimo',
            'Zanjitas',           'La Vertiente',     'Las Aguadas',
            'Las Chacras',        'Las Lagunas',      'Paso Grande',
            'Villa de Praga'
          ],
        'Santa Cruz': [
            'Puerto San Julián', 'Puerto Santa Cruz', 'Río Gallegos', 'Río Turbio', 'Veintiocho de Noviembre', 'Caleta Olivia', 'Comandante Luis Piedrabuena', 'El Calafate', 'El Chaltén', 'Gobernador Gregores', 'Las Heras', 'Los Antiguos', 'Perito Moreno', 'Pico Truncado'
          ],
        'Santa Fe':[
            'Armstrong',
            'Las Parejas',
            'Las Rosas',
            'Casilda',
            'Frontera',
            'Rafaela',
            'San Vicente',
            'Sunchales',
            'Villa Constitución',
            'Firmat',
            'Rufino',
            'Venado Tuerto',
            'Villa Cañás',
            'Avellaneda',
            'Florencia',
            'Las Toscas',
            'Malabrigo',
            'Reconquista',
            'Villa Ocampo',
            'Cañada de Gómez',
            'Totoras',
            'Laguna Paiva',
            'Recreo',
            'San José del Rincón',
            'Santa Fe',
            'Santo Tomé',
            'Sauce Viejo',
            'Esperanza',
            'San Carlos Centro',
            'San Jerónimo Norte',
            'Tostado',
            'Arroyo Seco',
            'Funes',
            'Granadero Baigorria',
            'Pérez',
            'Pueblo Esther',
            'Rosario',
            'Villa Gobernador Gálvez',
            'Ceres',
            'San Cristóbal',
            'San Guillermo',
            'Suardi',
            'Romang',
            'San Javier',
            'Coronda',
            'Gálvez',
            'San Genaro',
            'San Justo',
            'Capitán Bermúdez',
            'Carcarañá',
            'Fray Luis Beltrán',
            'Puerto General San Martín',
            'Roldán',
            'San Lorenzo',
            'El Trébol',
            'San Jorge',
            'Sastre y Ortiz',
            'Calchaquí',
            'Vera',
            'Bouquet',
            'Montes de Oca',
            'Tortugas',
            'Arequito',
            'Arteaga',
            'Berabevú',
            'Bigand',
            'Chabas',
            'Chañar Ladeado',
            'Gödeken',
            'Los Molinos',
            'Los Quirquinchos',
            'San José de la Esquina',
            'Sanford',
            'Villada',
            'Angélica',
            'Ataliva',
            'Aurelia',
            'Bauer y Sigel',
            'Bella Italia',
            'Colonia Aldao',
            'Colonia Bicha',
            'Colonia Bigand',
            'Castellanos',
            'Colonia Cello',
            'Colonia Iturraspe',
            'Colonia Margarita',
            'Colonia Raquel',
            'Coronel Fraga',
            'Egusquiza',
            'Esmeralda',
            'Estación Clucellas',
            'Eusebia y Carolina',
            'Eustolia',
            'Fidela',
            'Galisteo',
            'Garibaldi',
            'Hugentobler',
            'Humberto Primo',
            'Josefina',
            'Lehmann',
            'María Juana',
  'Colonia Maua',
  'Plaza Clucellas',
  'Presidente Roca',
  'Pueblo Marini',
  'Ramona',
  'Saguier',
  'San Antonio',
  'Santa Clara de Saguier',
  'Susana',
  'Tacural',
  'Tacurales',
  'Vila',
  'Villa San José',
  'Virginia',
  'Zenón Pereyra',
  'Alcorta',
  'Bombal',
  'Cañada Rica',
  'Cepeda',
  'Empalme Villa Constitución',
  'General Gelly',
  'Godoy',
  'Juan B. Molina',
  'Juncal',
  'La Vanguardia',
  'Máximo Paz',
  'Pavón',
  'Pavón Arriba',
  'Peyrano',
  'Rueda',
  'Santa Teresa',
  'Sargento Cabral',
  'Theobald',
  'Cayastá',
  'Colonia Mascías',
  'Helvecia',
  'Saladero Mariano Cabal',
  'Santa Rosa de Calchines',
  'Aarón Castellanos',
  'Amenábar',
  'Cafferata',
  'Cañada del Ucle',
  'Carmen',
  'Carreras',
  'Chapuy',
  'Chovet',
  'Christophersen',
  'Diego de Alvear',
  'Elortondo',
  'Hughes',
  'La Chispa',
  'Labordeboy',
  'Lazzarino',
  'Maggiolo',
  'María Teresa',
  'Melincué',
  'Miguel Torres',
  'Murphy',
  'San Eduardo',
  'San Francisco de Santa Fe',
  'San Gregorio',
  'Sancti Spiritu',
  'Santa Isabel',
  'Teodelina',
  'Wheelwright',
  'Arroyo Ceibal',
  'Berna',
  'El Araza',
  'El Rabón',
  'El Sombrerito',
  'Guadalupe Norte',
  'Ingeniero Chanourdie',
  'La Sarita',
  'Lanteri',
  'Las Garzas',
  'Los Laureles',
  'Nicanor Molinas',
  'San Antonio de Obligado',
  'Tacuarendi',
  'Villa Ana',
  'Villa Guillermina',
  'Bustinza',
  'Carrizales',
  'Classon',
  'Correa',
  'Lucio V. López',
  'Oliveros',
  'Pueblo Andino',
  'Salto Grande',
  'Serodino',
  'Villa Eloísa',
  'Arroyo Aguiar',
  'Arroyo Leyes',
  'Cabal',
  'Campo Andino',
  'Candioti',
  'Emilia',
  'Llambí Campbell',
  'Monte Vera',
  'Nelson',
  'Cavour',
  'San José',
  'Cululú',
  'Elisa',
  'Empalme San Carlos',
  'Felicia',
  'Franck',
  'Grutly',
  'Hipatía',
  'Humboldt',
  'Ituzaingó',
  'Jacinto L. Aráuz',
  'La Pelada',
  'Las Tunas',
  'María Luisa',
  'Matilde',
  'Nuevo Torino',
  'Pilar',
  'Progreso',
  'Providencia',
  'Pujato Norte',
  'Rivadavia',
  'Sa Pereyra',
  'San Agustín',
  'San Carlos Norte',
  'San Carlos Sud',
  'San Jerónimo del Sauce',
  'San Mariano',
  'Santa Clara de Buena Vista',
  'Santa María Centro',
  'Santa María Norte',
  'Santo Domingo',
  'Sarmiento',
  'Soutomayor',
  'Esteban Rams',
  'Gato Colorado',
  'Gregoria Pérez de Denis',
  'Juan de Garay',
  'Logroño',
  'Montefiore',
  'Pozo Borrado',
  'San Bernardo',
  'Santa Margarita',
  'Villa Minetti',
  'Acebal',
  'Albarellos',
  'Álvarez',
  'Alvear',
  'Arminda',
  'Carmen del Sauce',
  'Coronel Bogado',
  'Fighiera',
  'General Lagos',
  'Ibarlucea',
  'Piñero',
  'Pueblo Muñoz',
  'Soldini',
  'Uranga',
  'Villa Amelia',
  'Zavalla',
  'Coronel Domínguez',
  'Aguará Grande',
  'Ambrosetti',
  'Arrufo',
  'Capivara',
  'Colonia Ana',
  'Colonia Bossi',
  'Colonia Rosa',
  'Constanza',
  'Curupaity',
  'Dos Rosas y La Legua',
  'Hersilia',
  'Huanqueros',
  'La Cabral',
  'Colonia Clara',
  'La Lucila',
  'La Rubia',
  'Las Avispas',
  'Las Palmeras',
  'Moisés Ville',
  'Monigotes',
  'Monte Oscuridad',
  'Ñanducita',
  'Palacios',
  'Portugalete',
  'Santurce',
  'Soledad',
  'Villa Saralegui',
  'Villa Trinidad',
  'Alejandra',
  'Cacique Ariacaiquín',
  'Colonia Durán',
  'La Brava',
  'Arocena',
  'Barrancas',
  'Bernardo de Irigoyen',
  'Campo Piaggio',
  'Casalegno',
  'Centeno',
  'Desvío Arijón',
  'Díaz',
  'Gaboto',
  'Gessler',
  'Irigoyen',
  'Larrechea',
  'Loma Alta',
  'López',
  'Maciel',
  'Monje',
  'San Eugenio',
  'San Fabián',
  'Angeloni',
  'Cayastacito',
  'Colonia Dolores',
  'Esther',
  'Gobernador Crespo',
  'La Camila',
  'La Criolla',
  'La Penca y Caraguatá',
  'Marcelino Escalada',
  'Naré',
  'Pedro Gómez Cello',
  'Ramayón',
  'San Bernardo',
  'San Martín Norte',
  'Silva',
  'Vera y Pintado',
  'Videla',
  'Aldao',
  'Coronel Arnold',
  'Fuentes',
  'Luis Palacios',
  'Pujato',
  'Ricardone',
  'San Jerónimo Sud',
  'Timbúes',
  'Villa Mugueta',
  'Cañada Rosquín',
  'Carlos Pellegrini',
  'Casas',
  'Castelar',
  'Colonia Belgrano',
  'Crispi',
  'Landeta',
  'Las Bandurrias',
  'Las Petacas',
  'Los Cardos',
  'María Susana',
  'Piamonte',
  'San Martín de las Escobas',
  'Traill',
  'Cañada Ombú',
  'Fortín Olmos',
  'Garabato',
  'Golondrina',
  'Intiyaco',
  'La Gallareta',
  'Los Amores',
  'Los Tábanos',
  'Margarita',
  'Tartagal',
  'Toba'
          ],
          'Santiago del Estero': [
            'Añatuya', 'Bandera Beltrán', 'Campo Gallo', 'Clodomira', 'Colonia Dora', 'Fernández', 'Frías', 'Ingeniero Forres', 'La Banda', 'Loreto', 'Los Juríes', 'Los Telares', 'Monte Quemado', 'Nueva Esperanza', 'Pampa de los Guanacos', 'Pinto', 'Pozo Hondo', 'Quimilí', 'San Pedro de Guasayán', 'Santiago del Estero', 'Selva', 'Sumampa', 'Suncho Corral', 'Termas de Río Hondo', 'Tintina', 'Villa Atamisqui', 'Villa Ojo de Agua'
        ],
        'Tierra del Fuego': [
            'Ushuaia', 'Río Grande', 'Tolhuin'
          ],
        'Tucumán': [
            'Burruyacú',
            'San Miguel de Tucumán',
            'Alderetes',
            'Banda del Río Salí',
            'Concepción',
            'Famaillá',
            'Graneros',
            'Juan Bautista Alberdi',
            'La Cocha',
            'Bella Vista',
            'San Isidro de Lules',
            'Monteros',
            'Aguilares',
            'Simoca',
            'Tafí del Valle',
            'Las Talitas',
            'Tafí Viejo',
            'Trancas',
            'Yerba Buena',
            '7 de Abril',
            'El Chañar',
            'El Naranjo y El Sunchal',
            'El Puestito',
            'El Timbó',
            'Garmendia',
            'Gobernador Piedrabuena',
            'La Ramada y La Cruz',
            'Benjamín Aráoz y El Tajamar',
            'Villa Padre Monti',
            'Colombres',
            'Delfín Gallo',
            'El Bracho y El Cevilar',
            'El Naranjito',
            'La Florida y Luisiana',
            'Las Cejas',
            'Los Bulacio y Los Villagra',
            'Los Pereyra',
            'Los Pérez',
            'Los Ralos',
            'Ranchillos y San Miguel',
            'San Andrés',
            'Alpachiri y El Molino',
            'Alto Verde y Los Guchea',
            'Arcadia',
            'Gastona y Belicha',
            'La Trinidad',
            'Medina',
            'Lamadrid',
            'Taco Ralo',
            'Escaba',
            'Villa Belgrano',
            'El Sacrificio',
            'Huasa Pampa',
            'Rumi Punco',
            'San Ignacio',
            'San José de la Cocha',
            'Yánima y El Corralito',
            'Agua Dulce y La Soledad',
            'El Mojón',
            'Esquina y Mancopa',
            'Estación Aráoz y Tacanas',
            'Las Talas',
            'Los Gómez',
            'Los Puestos',
            'Manuel García Fernández',
            'Quilmes y Los Sueldos',
            'Río Colorado',
            'Santa Rosa de Leales y Laguna Blanca',
            'Villa de Leales',
            'El Manantial',
            'San Felipe y Santa Bárbara',
            'San Pablo y Villa Nougués',
            'Acheral',
            'Amberes',
            'Capitán Cáceres',
            'El Cercado',
            'León Rouges y Santa Rosa',
            'Los Sosa',
            'Río Seco',
            'Santa Lucía',
            'Sargento Moya',
            'Soldado Maldonado',
            'Teniente Berdina',
            'Villa Quinteros',
            'El Polear y Los Córdoba',
            'Los Sarmiento y La Tipa',
            'Monte Bello',
            'Santa Ana',
            'Atahona',
            'Buena Vista',
            'Ciudacita',
            'Manuela Pedraza',
            'Monteagudo',
            'Pampa Mayo',
            'Río Chico y Nueva Trinidad',
            'San Pedro y San Antonio',
            'Santa Cruz y La Tuna',
            'Villa Chicligasta',
            'Yerba Buena',
            'Amaicha del Valle',
            'Colalao del Valle',
            'El Mollar',
            'Raco',
            'Anca Juli',
            'El Cadillal',
            'La Esperanza',
            'Los Nogales',
            'Choromoro',
            'San Pedro de Colalao',
            'Tapia',
            'Cevil Redondo',
            'San Javier'
          ]
      };

    return regionsForArgentina
} 